// Garden Outside: original interactive chapter expansion inspired by nine supplied images.
let cutWalls=[],seated=null,echoState=null,echoModel=null,echoTime=0,echoRecord=null,echoClock=0,actorPads=[],deer=null,shadowMesh=null,shadowLength=0,shadowCaster=null,shadowLamp=null,homeToken=null,chorus=[],choirCharge=0,gardenTime=0;
function isLightKind(kind){return kind==='lamp'||kind==='moon'}
function resetExpansion(){cutWalls=[];seated=null;echoState=null;echoModel=null;echoTime=0;echoRecord=null;echoClock=0;actorPads=[];deer=null;shadowMesh=null;shadowLength=0;shadowCaster=null;shadowLamp=null;homeToken=null;chorus=[];choirCharge=0;gardenTime=0;$('echoStatus').hidden=true;}
function roofGeometry(){const s=new THREE.Shape();s.moveTo(-.62,0);s.lineTo(.62,0);s.lineTo(0,.5);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:1.12,bevelEnabled:false});g.translate(0,.5,-.56);return g}
function houseModel(wall='#eadbb1',roof='#a33122'){const g=new THREE.Group();box(1,1,1,0,0,0,wall,g);const r=new THREE.Mesh(roofGeometry(),mat(roof));r.castShadow=true;g.add(r);box(.22,.63,.025,0,-.185,.51,'#183344',g);for(const x of [-.32,.32])for(const y of [-.15,.25]){box(.2,.2,.024,x,y,.512,'#f2eee1',g);box(.145,.145,.03,x,y,.531,'#324a58',g)}box(.11,.5,.13,.3,.74,-.18,roof,g);return g}
function effigyModel(echo=false){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.16,.25,.8,8),mat('#ad2a1b'));body.position.y=-.06;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.12,12,8),mat('#dbbb98'));head.position.y=.47;g.add(head);for(const x of [-.21,.21])box(.09,.73,.18,x,-.04,0,'#171e1c',g);box(.29,.03,.2,0,.35,0,'#e5d9bd',g);if(echo)g.traverse(o=>{if(o.isMesh){o.material=new THREE.MeshBasicMaterial({color:'#78dcc7',transparent:true,opacity:.42,depthWrite:false});o.castShadow=false}});return g}
function cube(x,z,size=.75,kind='cube',y=0,id=null){const c=cubeBase(x,z,size,kind,y,id);if(['house','effigy','moon'].includes(kind)){const light=c.userData.light;c.clear();if(light)c.add(light);c.material=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});if(kind==='house')c.add(houseModel());if(kind==='effigy')c.add(effigyModel());if(kind==='moon'){const m=new THREE.Mesh(new THREE.SphereGeometry(.48,24,16),new THREE.MeshStandardMaterial({color:'#f3efdc',emissive:'#b9d5ed',emissiveIntensity:.75,roughness:.95}));c.add(m);for(let i=0;i<7;i++){const crater=new THREE.Mesh(new THREE.SphereGeometry(.04+i*.003,8,6),mat('#a7b6bf'));crater.position.set(Math.sin(i*2.3)*.26,Math.cos(i*1.7)*.24,.37);c.add(crater)}}}return c}
function arch(x,z,y=0,radius=1.6,column=2.4,color='#d8ad91',parent=world){for(const a of [-1,1]){const m=new THREE.Mesh(new THREE.CylinderGeometry(.12,.16,column,12),mat(color));m.position.set(x+a*radius,y+column/2,z);parent.add(m)}const top=new THREE.Mesh(new THREE.TorusGeometry(radius,.12,8,56,Math.PI),mat(color));top.position.set(x,y+column,z);parent.add(top)}
function topiaryField(cx,cz,count=85,spread=35){const geo=new THREE.ConeGeometry(.75,5.5,9),material=mat('@hedge');const inst=new THREE.InstancedMesh(geo,material,count);const m=new THREE.Object3D();for(let i=0;i<count;i++){const a=i*2.399,rad=7+(i*13%100)/100*spread;m.position.set(cx+Math.cos(a)*rad,1.6+(i%4)*.7,cz+Math.sin(a)*rad);m.scale.set(.6+(i%4)*.18,1+(i%5)*.3,.7+(i%3)*.15);m.updateMatrix();inst.setMatrixAt(i,m.matrix)}inst.castShadow=true;inst.receiveShadow=true;world.add(inst)}
function hedge(w,h,d,x,z,y=0,solid=true){const wall=box(w,h,d,x,y+h/2,z,'@hedge',world,solid);const count=Math.max(8,Math.round(w*h*.8));const bush=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.32,0),mat('#25472a'),count);const o=new THREE.Object3D();for(let i=0;i<count;i++){o.position.set(x+(i*.618%1-.5)*w,y+.2+(i*.382%1)*(h-.4),z+d/2+.05);o.scale.setScalar(.65+(i%5)*.12);o.updateMatrix();bush.setMatrixAt(i,o.matrix)}world.add(bush);wall.userData.foliage=bush;return wall}
function cutPanel(x,z,width=3.2,height=4.5,kind='hedge'){const m=kind==='hedge'?hedge(width,height,.5,x,z):box(width,height,.2,x,height/2,z,P.white,world,true);m.userData.cutId='cut'+cutWalls.length;m.userData.cuttable=true;m.userData.panelKind=kind;cutWalls.push(m);const mark=new THREE.Mesh(new THREE.TorusGeometry(.45,.035,6,28,Math.PI*1.2),new THREE.MeshBasicMaterial({color:'#e1e6c7'}));mark.position.set(x,2.3,z+.3);world.add(mark);m.userData.mark=mark;return m}
function negativeModel(ghostly=false){const g=new THREE.Group();const hole=new THREE.Mesh(new THREE.CircleGeometry(1.1,48),new THREE.MeshBasicMaterial({color:'#071a1b',transparent:ghostly,opacity:ghostly?.6:1,side:THREE.DoubleSide}));hole.position.y=1.6;hole.scale.y=1.4;g.add(hole);const r=new THREE.Mesh(new THREE.TorusGeometry(1.13,.11,8,50),mat('#efeddf'));r.scale.y=1.4;r.position.y=1.6;g.add(r);return g}
function photoModel(type,ghostly=false,card=null){if(!['cutout','shadow'].includes(type)&&!(type==='copy'&&['house','effigy','moon'].includes(card?.kind)))return photoModelBase(type,ghostly,card);let g;if(type==='cutout')g=negativeModel(ghostly);else if(type==='shadow'){g=new THREE.Group();const len=card?.length||12,w=card?.width||3;box(w,.16,len,0,-.08,-len/2,'#132b25',g).userData.structSolid=true;for(const x of [-w/2,w/2])glowBox(.035,.025,len,x,.015,-len/2,'#d6bc75',g)}else{g=new THREE.Group();let model;if(card.kind==='house')model=houseModel();else if(card.kind==='effigy')model=effigyModel();else model=new THREE.Mesh(new THREE.SphereGeometry(.48,18,12),mat('#e4e9d9'));model.scale.setScalar(card.size);model.position.y=card.size/2;g.add(model)}if(ghostly)g.traverse(o=>{if(o.isMesh){o.material=new THREE.MeshBasicMaterial({color:'#7ce4bc',transparent:true,opacity:.35,depthWrite:false});o.castShadow=false}});return g}
function openCut(target,cardId){if(!target)return null;solidOn(target,false);if(target.userData.foliage)target.userData.foliage.visible=false;if(target.userData.mark)target.userData.mark.visible=false;const g=new THREE.Group();world.add(g);g.position.set(target.position.x,0,target.position.z);arch(0,0,0,1.38,1.5,'#efeddf',g);const w=target.userData.bb.max.x-target.userData.bb.min.x,h=target.userData.bb.max.y,side=(w-2.8)/2;for(const a of [-1,1]){const j=box(side,h,.4,a*(1.4+side/2),h/2,0,'#e6e2cc',g);addSolid(j)}const cap=box(2.8,h-3.2,.4,0,3.2+(h-3.2)/2,0,'#e6e2cc',g);addSolid(cap);const p={type:'cutout',group:g,cardId,pos:g.position.toArray(),yaw:0,cutId:target.userData.cutId,target};placed.push(p);return p}
function removePlaced(p){if(p.type==='cutout'){const t=cutWalls.find(w=>w.userData.cutId===p.cutId);if(t){solidOn(t,true);if(t.userData.foliage)t.userData.foliage.visible=true;if(t.userData.mark)t.userData.mark.visible=true}}removePlacedBase(p)}
function deployStructure(type,pos,yaw,cardId){if(type!=='shadow')return deployStructureBase(type,pos,yaw,cardId);const card=cards.find(c=>c.id===cardId),group=photoModel(type,false,card);group.position.copy(pos);group.rotation.y=yaw;world.add(group);group.traverse(o=>{if(o.userData.structSolid)addSolid(o)});const p={type,group,cardId,pos:pos.toArray(),yaw};placed.push(p);return p}
function updateGhost(){const c=cards[selected];if(!ghost||!c)return;if(c.type==='cutout'){ray.setFromCamera(new THREE.Vector2(),camera);const hit=ray.intersectObjects(usableSolids(),false)[0];const target=hit?.object?.userData.cuttable?hit.object:null;ghostValid=!!target&&hit.distance<10;ghost.userData.cutTarget=ghostValid?target:null;if(ghostValid){ghost.position.set(target.position.x,0,target.position.z+(player.pos.z>target.position.z?.32:-.32));ghost.rotation.y=player.pos.z>target.position.z?0:Math.PI;}else{const f=camera.getWorldDirection(new V());ghost.position.copy(camera.position).addScaledVector(f,3);ghost.position.y=player.pos.y-EYE;ghost.rotation.y=player.yaw;}ghost.traverse(o=>{if(o.isMesh)o.material.color.set(ghostValid?'#9aefce':'#d7a677')});return}if(c.type==='shadow'){const f=new V(-Math.sin(player.yaw),0,-Math.cos(player.yaw));const x=Math.round((player.pos.x+f.x*photoDist)*2)/2,z=Math.round((player.pos.z+f.z*photoDist)*2)/2,y=groundAt(x,z,player.pos.y+.2);ghost.position.set(x,Number.isFinite(y)?y+.015:0,z);ghost.rotation.y=Math.round(player.yaw/(Math.PI/2))*Math.PI/2+photoRot;ghost.updateMatrixWorld(true);const end=ghost.localToWorld(new V(0,0,-c.length+.2));const ey=groundAt(end.x,end.z,y+.4);ghostValid=Number.isFinite(y)&&Math.abs(ey-y)<.3;ghost.traverse(o=>{if(o.isMesh)o.material.color.set(ghostValid?'#83e5b2':'#ffc377')});return}updateGhostBase()}
function place(){if(!photoMode)return;const c=cards[selected];if(c?.type==='cutout'){if(!ghostValid||!ghost?.userData.cutTarget){showToast('将负片对准带白弧标记的绿篱或幕布。');return}snapshot();openCut(ghost.userData.cutTarget,c.id);stopPhoto();flash();tone(420,.7);showToast('留白变成了通道。走过去后，可按 X 收回留白。',5);return}placeBase()}
function capture(){if(level===9&&shadowMesh&&!held&&!photoMode){ray.setFromCamera(new THREE.Vector2(),camera);const hit=ray.intersectObjects([shadowMesh,...usableSolids(),...cubes],true)[0];if(hit?.object===shadowMesh&&hit.distance<28){cards=cards.filter(c=>c.type!=='shadow');renderer.render(scene,camera);addCard('shadow','影子也有重量',{length:Math.floor(shadowLength*2)/2,width:2.9,img:renderer.domElement.toDataURL('image/jpeg',.78)});flash();showToast('拍下了 '+(Math.floor(shadowLength*2)/2).toFixed(1)+' 米的影子。现在可像道路一样显影。',6);return}}captureBase();const c=cards[selected];if(c?.type==='copy'){c.name=c.kind==='house'?'一间可以携带的家':c.kind==='effigy'?'队列的副本':c.name;updateAlbum()}}
function actorPad(x,z,label,kind='any',y=0){const p={x,z,y,label,kind,on:false};box(1.7,.06,1.7,x,y+.03,z,'#3b3328');p.ring=ring(x,z,y+.06,.7,'#d3b571');floorSign(label,x,z+1.4,y,2.4);actorPads.push(p);return p}
function onSpot(pos,p,radius=.7){return Math.hypot(pos.x-p.x,pos.z-p.z)<radius&&Math.abs(pos.y-EYE-p.y)<.6}
function tickActorPads(){for(const p of actorPads){const live=onSpot(player.pos,p),echo=echoModel&&onSpot(new V(echoModel.position.x,echoModel.position.y+.95,echoModel.position.z),p),object=cubes.some(c=>c!==held?.obj&&c.userData.kind==='effigy'&&c.userData.size<=1.05&&Math.hypot(c.position.x-p.x,c.position.z-p.z)<.7&&Math.abs(c.position.y-c.userData.size/2-p.y)<.15);p.on=p.kind==='echo'?!!echo:p.kind==='player'?live:p.kind==='effigy'?object:p.kind==='empty'?!(live||echo||cubes.some(c=>c!==held?.obj&&Math.hypot(c.position.x-p.x,c.position.z-p.z)<.8)):!!(live||echo||object);p.ring.material.color.set(p.on?'#93dbb0':'#d3b571')}}
function toggleEcho(){if(level!==8&&level!==10){showToast('回声录制在合唱场与月亮庭院使用。');return}if(echoRecord){finishEcho();return}if(echoModel){world.remove(echoModel);echoModel=null}echoState=null;echoRecord=[];echoClock=0;echoTime=0;recordEchoPoint();showToast('正在录制回声。走到回声圈，按 V 停止；也会在 6 秒后自动结束。',6)}
function recordEchoPoint(){echoRecord.push({t:echoTime,pos:player.pos.toArray(),yaw:player.yaw})}
function finishEcho(){if(!echoRecord?.length)return;recordEchoPoint();echoState=echoRecord;echoRecord=null;echoTime=0;echoModel=effigyModel(true);echoModel.scale.setScalar(1.4);world.add(echoModel);showToast('回声会重走一次你的路线，然后留在终点。V 可以重新录制。',6);tone(520,.5)}
function tickEcho(dt){if(echoRecord){echoTime+=dt;echoClock+=dt;if(echoClock>=.08){echoClock=0;recordEchoPoint()}if(echoTime>=6)finishEcho();$('echoStatus').hidden=false;$('echoStatus').textContent='REC ● '+echoTime.toFixed(1)+' / 6.0 s · V 结束';}else if(echoState&&echoModel){echoTime+=dt;let a=echoState[0],b=echoState.at(-1);for(let i=1;i<echoState.length;i++){if(echoState[i].t>=echoTime){a=echoState[i-1];b=echoState[i];break}a=b=echoState[i]}const t=clamp((echoTime-a.t)/(b.t-a.t||1),0,1);echoModel.position.fromArray(a.pos).lerp(new V(...b.pos),t);echoModel.position.y-=.95;echoModel.rotation.y=a.yaw;$('echoStatus').hidden=false;$('echoStatus').textContent=echoTime>=echoState.at(-1).t?'回声已留在终点 · V 重录':'回声正在重走你的路线';}else $('echoStatus').hidden=true}
function seat(x,z,y=0,rot=0){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=rot;g.userData={type:'seat',view:new V(x,y+1.3,z),yaw:rot};world.add(g);const shell=new THREE.Mesh(new THREE.SphereGeometry(.62,20,14),new THREE.MeshStandardMaterial({color:'#b32920',roughness:.28}));shell.scale.set(1,.75,1);shell.position.y=.7;g.add(shell);box(.83,.17,.63,0,.78,.16,'#c34c37',g);box(.13,.57,.13,0,.28,0,'#b6aaa0',g);box(1,.05,.05,0,.04,0,'#b6aaa0',g);box(.05,.05,1,0,.04,0,'#b6aaa0',g);pickups.push(g);return g}
function action(){if(!photoMode&&!held){const o=aimTarget();if(o?.userData.type==='seat'){seated=o;player.pos.copy(o.userData.view);player.yaw=o.userData.yaw;player.pitch=.1;syncCamera();showToast('坐稳了。看向月亮，WASD 或空格起身。',5);return}if(o?.userData.type==='return'){leaveHouse();return}}actionBase()}
function stepPlayer(dt){if(seated){if(keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD||keys.Space){player.pos.y=seated.position.y+EYE;player.pos.z+=1.1;seated=null}else{if(keys.ArrowLeft)player.yaw+=dt*1.5;if(keys.ArrowRight)player.yaw-=dt*1.5;if(keys.ArrowUp)player.pitch=clamp(player.pitch+dt,-1.35,1.3);if(keys.ArrowDown)player.pitch=clamp(player.pitch-dt,-1.35,1.3);syncCamera();return}}stepPlayerBase(dt)}
function enterHouse(){if(level!==6||held){return}const target=aimTarget();if(target?.userData.kind!=='house'){showToast('对准放大后的房门，按 F 进入。');return}if(target.userData.size<2.8){showToast('这扇门还容不下你。先把房子放大到至少 2.8 米。',5);return}if(camera.position.distanceTo(target.position)>5){showToast('再靠近房门一些。');return}flags.homeEntry=target.position.toArray();flags.enteredHome=true;player.pos.set(38,EYE,6);player.yaw=0;player.pitch=0;player.vy=0;checkpoint.set(38,EYE,6);flash();showToast('房子的内部，比外部多出一整座庭院。照片能把外面的光带进来。',6)}
function leaveHouse(){const p=flags.homeEntry||[0,1.4,0];player.pos.set(p[0],EYE,p[2]+4);player.yaw=0;player.vy=0;checkpoint.set(0,EYE,10);flash();showToast('又回到了卷起的街区。',3)}
function lampPost(x,z,height=4,scale=1,parent=world){const g=new THREE.Group();g.position.set(x,0,z);parent.add(g);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,height,10),mat('#a5843e'));stem.position.y=height/2;g.add(stem);const shade=new THREE.Mesh(new THREE.ConeGeometry(.55*scale,.33*scale,24,1,true),new THREE.MeshStandardMaterial({color:'#f4e5bf',emissive:'#efdcaa',emissiveIntensity:.6,side:THREE.DoubleSide}));shade.position.y=height;g.add(shade);const base=new THREE.Mesh(new THREE.CylinderGeometry(.18,.2,.05,14),mat('#a5843e'));base.position.y=.025;g.add(base);return g}
function deerModel(){const g=new THREE.Group();const brown=mat('#a86931');const body=new THREE.Mesh(new THREE.SphereGeometry(.5,14,9),brown);body.scale.set(.48,.64,1.22);body.position.y=.9;g.add(body);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.1,.14,.58,9),brown);neck.position.set(0,1.2,-.46);neck.rotation.x=-.4;g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.17,12,8),brown);head.scale.z=1.55;head.position.set(0,1.52,-.68);g.add(head);for(const x of [-.12,.12]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.07,.24,7),brown);ear.position.set(x,1.73,-.68);ear.rotation.z=x*2;g.add(ear)}const legs=[];for(const x of [-.18,.18])for(const z of [-.38,.4]){const l=new THREE.Group();l.position.set(x,.8,z);g.add(l);box(.065,.65,.065,0,-.32,0,'#8d592d',l);legs.push(l)}g.userData.legs=legs;world.add(g);return g}
function updateAlbum(){updateAlbumBase();const c=cards[selected];const names={bridge:'桥',stairs:'楼梯',copy:'物体',cutout:'留白',shadow:'影子'};if(c){$('photoNote').textContent=c.type==='cutout'?'负片 · 对准白弧标记 · F 剪开':c.type==='shadow'?'影子道路 · 长 '+c.length.toFixed(1)+' m':c.type==='copy'?'物体快照 · '+c.size.toFixed(2)+' m · '+({house:'房子',effigy:'人偶',moon:'月光',lamp:'灯箱',cube:'方块'}[c.kind]||c.kind):$('photoNote').textContent;}$('album').replaceChildren();cards.forEach((card,i)=>{const b=document.createElement('button');b.className=i===selected?'selected':'';b.textContent=(i+1)+' '+names[card.type]+(placed.some(p=>p.cardId===card.id)&&card.type!=='copy'?' ↗':'');b.onclick=()=>selectCard(i);$('album').append(b)})}
function prompt(){promptBase();if(level<6)return;let msg=$('prompt').textContent;const o=!photoMode&&!held?aimTarget():null;if(photoMode&&cards[selected]?.type==='cutout')msg=ghostValid?'F · 把这片留白剪成入口':'将负片对准带白弧标记的墙';if(o?.userData.kind==='house')msg='E 拿起房子　'+(o.userData.size>=2.8?'F 进入房门':'推远放大后可进入');if(o?.userData.type==='return')msg='E · 回到屋外';if(o?.userData.type==='seat')msg='E · 坐下，从这里看';if(level===9&&!held&&!photoMode){ray.setFromCamera(new THREE.Vector2(),camera);if(shadowMesh&&ray.intersectObjects([shadowMesh,...usableSolids(),...cubes],true)[0]?.object===shadowMesh)msg='P · 拍下影子　'+shadowLength.toFixed(1)+' m'}if(seated)msg='沿着弧线看向月亮 · WASD / 空格起身';$('prompt').textContent=msg;$('prompt').hidden=!msg;}
function makeHouseWave(){const verts=[],idx=[],r=20,steps=40;for(let i=0;i<=steps;i++){const t=i/steps*2.22;for(const z of [-32,28])verts.push(-9-r*Math.sin(t),r*(1-Math.cos(t))-.15,z)}for(let i=0;i<steps;i++){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(idx);geo.computeVertexNormals();const skin=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#345128',roughness:1,side:THREE.DoubleSide}));skin.receiveShadow=true;world.add(skin);const count=96,body=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),mat('#e8d9aa'),count),roof=new THREE.InstancedMesh(roofGeometry(),mat('#b83323'),count),windows=new THREE.InstancedMesh(new THREE.BoxGeometry(.2,.2,.035),mat('#233d4f'),count*4),o=new THREE.Object3D(),tmp=new THREE.Object3D();for(let i=0;i<count;i++){const row=i%6,col=Math.floor(i/6),t=.06+row*.36,scale=1.6+(col%3)*.22;o.position.set(-9-r*Math.sin(t),r*(1-Math.cos(t)), -28+col*3.5);o.rotation.z=-t;o.scale.setScalar(scale);o.translateY(.5*scale);o.updateMatrix();body.setMatrixAt(i,o.matrix);body.setColorAt(i,new THREE.Color(['#e7dcae','#e7c7b7','#dfe9dd','#efdfad'][i%4]));roof.setMatrixAt(i,o.matrix);roof.setColorAt(i,new THREE.Color(['#a83226','#496765','#ad402b','#1f3f54'][i%4]));let j=0;for(const x of [-.32,.32])for(const y of [-.15,.25]){tmp.position.set(x,y,.518);tmp.updateMatrix();windows.setMatrixAt(i*4+j++,o.matrix.clone().multiply(tmp.matrix))}}body.castShadow=true;roof.castShadow=true;world.add(body,roof,windows);}
function buildHouseWave(){setupLight();scene.background.set('#164e72');scene.fog=new THREE.Fog('#164e72',65,160);floor(18,32,0,0,0,'@grass');makeHouseWave();topiaryField(-27,-12,65,15);homeToken=cube(0,3,.65,'house');cube(4,7,.55,'lamp');floorSign('房子的大小，由你决定',0,6,0,5);floorSign('F · 进入放大的房门',0,10,0,4.5);for(const x of [6,8])seat(x,1,0,.7);floor(14,25,38,-2,0,'@red');for(const x of [31,45]){hedge(.8,7,25,x,-2,0,true);for(let z=7;z>-14;z-=5)arch(x,z,0,1.6,2.5,'#c3976b')}const door=box(2.2,3.3,.18,38,1.65,8,'#194b4a');door.userData={type:'return'};pickups.push(door);sign('E / 回到屋外',38,3.8,7.85,3,.6,'#e5c895',null,Math.PI);sensor(41,-6,1.4);gate(38,-12);sign('HOME IS LARGER ON THE INSIDE',38,5,-13,11,1,'#dfc09f');flags.enteredHome=false;}
function barrier(z){for(const x of [-4,0,4])cutPanel(x,z);for(const [a,b] of [[-8,-5.6],[-2.4,-1.6],[1.6,2.4],[5.6,8]])hedge(b-a,6,.6,(a+b)/2,z);box(16,1.5,.6,0,5.25,z,'@hedge',world,true)}
function buildHedgeMemory(){setupLight();scene.background.set('#77909b');scene.fog=new THREE.Fog('#557269',36,85);floor(16,43,0,-5.5,0,'@grass');hedge(.9,11,43,-8,-5.5);hedge(.9,11,43,8,-5.5);hedge(16,11,.9,0,16);barrier(1);barrier(-11);for(const x of [-2,2]){hedge(.7,6,8,x,7);hedge(.7,6,6,x,-7)}deer=deerModel();deer.position.set(-4,0,6);deer.userData.path=[];addCard('cutout','鹿走过的留白');floorSign('白色是没有墙的地方',0,12,0,5.5);const g=gate(0,-24);flags.mazeStage=0;flags.mazeLoops=0;flags.deerStage=0;for(const x of [-5,5])topiaryField(x,-21,20,8);sign('FOLLOW WHAT DOES NOT REPEAT',0,5,-25,10,.8,'#dde3ce');}
function buildChoir(){setupLight('night');scene.background.set('#181e19');scene.fog=new THREE.Fog('#181e19',40,120);floor(24,34,0,0,0,'@grass');for(let row=0;row<7;row++)for(let col=0;col<12;col++){const x=-16+col*2.9,z=-12-row*3;if(Math.abs(x)<5&&z>-25)continue;const g=effigyModel();g.position.set(x,1.4,z);g.scale.setScalar(2.1);world.add(g);chorus.push(g)}cube(0,-11,1.35,'effigy');actorPad(-4,-4,'I · 回声','echo');actorPad(0,-4,'II · 来客','player');actorPad(4,-4,'III · 人偶','effigy');actorPad(0,-11,'IV · 留空','empty');for(const x of [-5,5])lampPost(x,10,3);gate(0,-15);sign('THE CHOIR NEEDS ONE ABSENCE',0,6,-16,12,1,'#e0c0a3');floorSign('V · 录下你的路线',-4,5,0,5);floorSign('人偶 ≤ 1.05 m',4,0,0,3.3);flags.chorusOpen=false;choirCharge=0;}
function buildShadowField(){setupLight('night');scene.background.set('#632916');scene.fog=new THREE.Fog('#632916',40,110);floor(24,14,0,8,0,'@red');floor(18,15,0,-16.5,0,'@red');for(const x of [-10,-6,6,10])for(const z of [12,4,-12,-20])lampPost(x,z,2.6+(Math.abs(z)%3)*.3);shadowLamp=new V(0,4,8.5);lampPost(0,8.5,4,1.5);const light=new THREE.PointLight('#ffe6b0',16,30,1.8);light.position.copy(shadowLamp);world.add(light);shadowCaster=cube(2,5,.8,'effigy');ring(0,2.5,0,1.2,'#e0bf7b');floorSign('让影子先抵达对岸',0,5,0,5.4);dock(0,2,0,'影子显影');shadowMesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({color:'#111c19',transparent:true,opacity:.95,side:THREE.DoubleSide}));shadowMesh.rotation.x=-Math.PI/2;shadowMesh.position.y=.035;world.add(shadowMesh);gate(0,-21).open=true;sign('LIGHT REMEMBERS YOUR HEIGHT',0,6,-23,13,1,'#e6c094');flags.shadowAligned=false;}
function makeRoad(){const segments=70;for(let i=0;i<segments;i++){const t=(i+.5)/segments,x=42+3.3*Math.sin(t*Math.PI*2),z=6-t*29,y=t*2.4;const road=box(3.5,.3,.66,x,y-.15,z,'#b6b0a1',world,true);road.rotation.y=Math.atan2(-3.3*Math.PI*2*Math.cos(t*Math.PI*2),29);refresh(road);const center=glowBox(.045,.015,.55,0,.165,0,'#f4dc96',road);for(const a of [-1,1])glowBox(.055,.018,.66,a*1.67,.165,0,'#f5efe1',road);}floor(11,10,42,-27,2.4,'@grass');}
function palace(){for(let i=0;i<16;i++){const x=24+i*2.1,h=20-i*1.05;box(2.12,h,3.5,x,h/2,-35,'#dca58d');box(2.12,.2,3.7,x,h+.1,-35,'#f0ded0');for(let j=1;j<h-1;j+=1.5)box(.65,.45,.22,x,j,-33.12,'#172f4b')}for(let i=-4;i<=4;i++){if(!i)continue;arch(42+i*3.4,-29,2.4,1.35,3.5,'#e4c0a0')}const oval=new THREE.Mesh(new THREE.TorusGeometry(3.8,.19,10,80),mat('#e4bf99'));oval.position.set(42,8.4,-30);oval.scale.y=1.6;world.add(oval);const sky=new THREE.Mesh(new THREE.CircleGeometry(3.7,64),new THREE.MeshBasicMaterial({color:'#0c284c',side:THREE.DoubleSide}));sky.position.set(42,8.4,-38);sky.scale.y=1.6;world.add(sky);const moon=new THREE.Mesh(new THREE.SphereGeometry(.7,26,18),new THREE.MeshStandardMaterial({color:'#d8e5e5',emissive:'#647a96',emissiveIntensity:.8,roughness:1}));moon.position.set(42,8,-36.8);world.add(moon);}
function buildMoonRoad(){setupLight('night',42);scene.background.set('#853716');scene.fog=new THREE.Fog('#853716',80,180);floor(15,21,0,3,0,'@stone');for(let i=0;i<8;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(5+i%3,10+i%4*3,8),mat('@stone'));m.position.set((i%2?1:-1)*(9+i*.7),2,-8-i*2);world.add(m)}makeRoad();palace();topiaryField(42,-31,95,18);teleportPair({x:0,z:-7},{x:42,z:6});const poster=cutPanel(0,-6.8,6,7,'screen');const pc=new THREE.PerspectiveCamera(55,6/7,.1,100);pc.position.set(42,7,15);pc.lookAt(42,.7,-12);renderer.render(scene,pc);const img=new Image(),tx=new THREE.Texture(img);tx.colorSpace=THREE.SRGBColorSpace;img.onload=()=>tx.needsUpdate=true;img.src=renderer.domElement.toDataURL('image/jpeg',.8);if(img.complete)tx.needsUpdate=true;poster.material=new THREE.MeshBasicMaterial({map:tx});for(const x of [-5,5])lampPost(x,6,3);addCard('cutout','给风景剪一个入口');sign('THIS ROAD IS STILL A PICTURE',0,8,-7,10,1,'#edd9b7');const chair=seat(42,-23,2.4,0);for(const x of [37,47])seat(x,-19,2.4,.4);actorPad(38,-25,'留下一段回声','echo',2.4);sensor(46,-25,3.8);box(.8,1.2,.5,46,3,-25,P.dark);ring(46,-25,2.4,.8,P.teal);makeAlignment(new V(42,3.7,-23),new V(42,8,-36.8),()=>{renderer.render(scene,camera);addCard('copy','一小片月亮',{kind:'moon',size:.55,img:renderer.domElement.toDataURL('image/jpeg',.8)});flags.moonRemembered=true;showToast('月光被记进照片。留一段回声，再把月光显影在右侧接收器附近。',7)},2.4);gate(42,-29,2.4);flags.moonRemembered=false;flags.moonExit=false;choirCharge=0;}
function tickExpansion(dt){gardenTime+=dt;tickEcho(dt);tickActorPads();if(level===6){const on=sensors[0].on&&flags.enteredHome;gates[0].open=on;$('objective').textContent=on?'屋里的窗已被点亮。穿过这座比房子更大的庭院。':player.pos.x>25?'用照片把外面的灯带进来，在接收器附近显影。':homeToken&&homeToken.userData.size>=2.8?'房门已足够大。靠近并瞄准它，F 进入。':'给灯拍一张照片，再把小房子放大到至少 2.8 米。';}
if(level===7){const stage=flags.mazeStage;if(stage===0&&player.pos.z<-2){if(player.pos.x<-2.4){flags.mazeStage=1;checkpoint.set(-4,EYE,-3);deer.userData.path=[new V(-4,0,-3),new V(4,0,-3),new V(4,0,-8)];showToast('这一段墙没有重复。收回留白，跟上鹿的下一次转弯。',6)}else{player.pos.set(0,EYE,13);flags.mazeLoops++;showToast('相同的墙把你送回来了。鹿停在左边。',5)}}if(stage===1&&player.pos.z<-13){if(player.pos.x>2.4){flags.mazeStage=2;deer.userData.path=[new V(4,0,-16),new V(0,0,-21)];showToast('留白接成了一条真正的路。',5)}else{player.pos.copy(checkpoint);showToast('又回到转弯处。这次留意鹿去往右边。',5)}}let target=deer.userData.path?.[0]||new V(-4,0,3);const d=target.clone().sub(deer.position);if(d.length()>.1){deer.position.addScaledVector(d.normalize(),Math.min(dt*2.2,target.distanceTo(deer.position)));deer.rotation.y=Math.atan2(-d.x,-d.z);deer.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(gardenTime*7+i*Math.PI)*.35)}else if(deer.userData.path?.length)deer.userData.path.shift();gates[0].open=flags.mazeStage===2;$('objective').textContent=flags.mazeStage===2?'跟着鹿离开绿篱。':flags.mazeStage===1?'走过第一处留白后，X 收回。下一片留白应该在哪里？':'C 举起负片，对准白弧标记。鹿记得不重复的方向。';}
if(level===8){const ok=actorPads.every(p=>p.on);choirCharge=ok?choirCharge+dt:0;if(choirCharge>2&&!flags.chorusOpen){flags.chorusOpen=true;chime();showToast('队列终于容得下一个空位。',5)}gates[0].open=flags.chorusOpen;for(let i=0;i<chorus.length;i++)chorus[i].rotation.y=flags.chorusOpen?Math.sin(i)*.15:.025*Math.sin(gardenTime*.4+i);$('objective').textContent=flags.chorusOpen?'合唱已经结束。走过那处被允许的空位。':actorPads.map(p=>p.label+' '+(p.on?'✓':'○')).join('　');}
if(level===9){shadowCaster=cubes.find(c=>c.userData.kind==='effigy')||shadowCaster;const c=shadowCaster,s=c.userData.size,aligned=c!==held?.obj&&Math.abs(c.position.x)<.8&&Math.abs(c.position.z-2.5)<1.1&&Math.abs(c.position.y-s/2)<.15;flags.shadowAligned=aligned;shadowLength=clamp((shadowLamp.z-c.position.z)*s/Math.max(.35,shadowLamp.y-s),1,20);shadowMesh.visible=aligned;shadowMesh.scale.set(2.9,shadowLength,1);shadowMesh.position.set(c.position.x,.035,c.position.z-shadowLength/2);shadowMesh.updateMatrixWorld(true);$('objective').textContent=cards.some(c=>c.type==='shadow')?'照片已保留影长。先移开人偶，再将影子显影成路。':aligned?'影长 '+shadowLength.toFixed(1)+' m · 站到一旁，P 拍摄地上的影子。':'把红色人偶放在圆环上；推远放大，影子会先抵达对岸。';}
if(level===10){if(player.pos.x>25)checkpoint.set(42,4.05,-23);updateAlignment(dt,!!seated);const ok=actorPads[0].on&&sensors[0].on&&flags.moonRemembered;choirCharge=ok?choirCharge+dt:0;if(choirCharge>1&&!flags.moonExit){flags.moonExit=true;flash();chime();showToast('你留下了回声，把月亮带回了地面。',6)}gates[0].open=flags.moonExit;$('objective').textContent=flags.moonExit?'月亮已经停在你这一边。走进最后的拱门。':player.pos.x<25?'对公路幕布使用留白负片，走进画面里的道路。':!flags.moonRemembered?'沿弯路上行，在中间的红椅坐下，让圆弧围住月亮。':'回声 '+(actorPads[0].on?'✓':'○')+'　月光 '+(sensors[0].on?'✓':'○')+'　· 让两者同时停留在庭院。';}}
chapters.push(
{title:'卷起的街区',sub:'07 / THE HOUSE HOLDS MORE THAN ITS SIZE',goal:'给光留下副本，把一间小房子变成可以进入的家。',intro:'这些房子随着草地卷了起来。但你可以带走其中一间。',hints:['对灯箱按 P 拍照，保留一份光；再对小房子按 E 拿起。','平视并向远处推送，把房子放大到至少 2.8 米，再放下。','靠近并瞄准放大的房子，按 F 进入。','屋内没有灯。C 举起灯箱照片，F 在接收器附近显影。E 可通过背后的门返回屋外。']},
{title:'鹿走过的留白',sub:'08 / THE MAZE REMEMBERS THE DEER',goal:'用一片留白，剪出两次正确的转弯。',intro:'你记得绿篱。鹿记得绿篱之间没有东西的地方。',hints:['相册里是一张留白负片。C 举起，对准有白弧标记的绿篱，F 剪出入口。','第一面墙选左侧通道。鹿在那里停留。错选会回到开头。','走过去后 X 收回留白，让后面的墙复原；留白可以重复使用。','在中间横向通道转到右边，在第二面墙再使用负片。从右侧通过，鹿会带你离开。']},
{title:'少一个人的合唱',sub:'09 / AN ABSENCE IS PART OF THE PATTERN',goal:'让回声、来客、人偶各就各位，第四个位置保持空白。',intro:'所有人都在重复同一个位置。只有空位还没有被允许。',hints:['把第四个圈里的红色人偶拿走，缩小到不超过 1.05 米，放进右侧“人偶”圈。','走到左侧“回声”圈，V 开始录制，停留片刻，再 V 结束。回声会留在录制终点。','你自己站进中间“来客”圈，保持约两秒。第四个圈必须没有任何人或物体。','若回声没有留在圈里，V 重录。出口打开后，队列会允许你通过。']},
{title:'影子先抵达',sub:'10 / DEVELOP THE SHADOW, NOT THE OBJECT',goal:'借灯与人偶拉长影子，再把影子变成路。',intro:'灯没有移动。变长的是另一个你。',hints:['将红色人偶放到断崖前的圆环上。放大到约 2.7–3.0 米，影子就会延伸到另一岸。','抬头或平视放大，然后放下。站到一旁，低头对准长影子按 P。','这次拍的是影子，不是人偶。照片应标为“影子道路”，长度大约 12–16 米。','照片会保留拍摄时的影长。先把人偶移开，再 C 举影子照片、F 显影，走上黑色的路。']},
{title:'月亮停在幕布背面',sub:'11 / LEAVE AN ECHO. TAKE THE MOON.',goal:'走入画面的路，从红椅借月光，留下回声后离开。',intro:'道路还在幕布上。月亮还在别人那一边。',hints:['对前方公路幕布使用留白负片。剪出入口后，穿过去进入真正的弯路。','沿弯曲上升的道路到高处庭院。靠近正中红椅按 E 坐下。','环顾，使三段弧线在月亮附近重合，保持视线。月光快照会进入相册。','在左侧回声圈录制并结束，让回声留在那里。再在右侧接收器附近显影月光。','回声与月光同时成立后，最后拱门会打开。WASD 或空格可以从椅子起身。']}
);
