'use strict';
const $=id=>document.getElementById(id),V=THREE.Vector3,clamp=THREE.MathUtils.clamp;
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.07,160);camera.rotation.order='YXZ';const ray=new THREE.Raycaster();
const EYE=1.65,R=.26,keys={},player={pos:new V(0,EYE,10),yaw:0,pitch:0,vy:0,grounded:true};
let world,level=0,active=false,begun=false,won=false,solids=[],cubes=[],pickups=[],cards=[],placed=[],gates=[],pads=[],portals=[],sensors=[],decorAnim=[],held=null,ghost=null,ghostValid=false,photoMode=false,selected=0,photoDist=2,photoRot=0,hasCamera=false,align=null,flags={},history=[],checkpoint=new V(0,EYE,10),elapsed=0,falls=0,frame=0,toastUntil=0,sensitivity=1,muted=false,portalCooldown=0,serial=0,unlocked=0,highQuality=true;
try{unlocked=clamp(Number(localStorage.getItem('borrowed-distance-iv'))||0,0,5)}catch(e){}
const P={white:'#e5e5e5',blue:'#676767',dark:'#303030',yellow:'#b7b7b7',teal:'#acacac',coral:'#7f7f7f',pink:'#919191'};
const mats=new Map(),textures=new Map();
function textureLegacy(kind){if(textures.has(kind))return textures.get(kind);const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d');g.fillStyle=kind==='hedge'?'#323232':kind==='grass'?'#5d5d5d':kind==='red'?'#383838':kind==='stone'?'#939393':kind==='wall'?'#bbbbbb':kind==='carpet'?'#717171':kind==='tile'?'#e3e3e3':'#606060';g.fillRect(0,0,128,128);let seed=913;for(let i=0;i<3000;i++){seed=(seed*16807)%2147483647;const x=seed%128;seed=(seed*16807)%2147483647;const y=seed%128;g.fillStyle=i%2?'#ffffff0b':'#00000012';g.fillRect(x,y,1,1)}if(kind==='wall'){g.strokeStyle='#8c895833';for(let x=8;x<128;x+=16){g.beginPath();g.moveTo(x,0);g.lineTo(x,128);g.stroke()}}if(kind==='tile'){g.strokeStyle='#758f9250';g.lineWidth=2;g.strokeRect(1,1,126,126);g.strokeRect(63,63,65,65);g.strokeRect(0,0,64,64)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(kind==='wall'?4:8,kind==='wall'?2:8);t.colorSpace=THREE.SRGBColorSpace;textures.set(kind,t);return t}
function matLegacy(color){if(!mats.has(color)){const m=new THREE.MeshStandardMaterial({color:color[0]==='@'?'#ffffff':color,roughness:.78});if(color[0]==='@')m.map=texture(color.slice(1));mats.set(color,m)}return mats.get(color)}
function boxPrevious(w,h,d,x,y,z,color=P.white,parent=world,solid=false){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);if(solid)addSolid(o);return o}
function addSolid(o){o.userData.collides=true;solids.push(o);refresh(o);return o}
function refresh(o){o.updateWorldMatrix(true,false);o.userData.bb=new THREE.Box3().setFromObject(o);}
function solidOn(o,on){o.userData.collides=on;o.visible=on;}
function floor(w,d,x,z,y=0,color=P.white){return box(w,.5,d,x,y-.25,z,color,world,true)}
function sign(txt,x,y,z,w=5,h=.8,color='#393939',bg=null,rot=0){const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d');if(bg){g.fillStyle=bg;g.fillRect(0,0,1024,256)}g.fillStyle=color;g.font='600 66px Arial, "Microsoft YaHei", sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(txt,512,128,985);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,transparent:!bg,side:THREE.DoubleSide}));m.position.set(x,y,z);m.rotation.y=rot;world.add(m);return m}
function floorSign(txt,x,z,y=0,w=3){const m=sign(txt,x,y+.025,z,w,.65);m.rotation.x=-Math.PI/2;return m}
function line(points,color=P.teal){const o=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(p=>new V(...p))),new THREE.LineBasicMaterial({color}));world.add(o);return o}
function ring(x,z,y=0,r=1,color=P.yellow){const m=new THREE.Mesh(new THREE.TorusGeometry(r,.027,6,60),new THREE.MeshBasicMaterial({color}));m.rotation.x=-Math.PI/2;m.position.set(x,y+.035,z);world.add(m);return m}
function dock(x,z,y=0,label='DEVELOP'){line([[x-1.6,y+.03,z+.4],[x+1.6,y+.03,z+.4],[x+1.6,y+.03,z-1],[x-1.6,y+.03,z-1],[x-1.6,y+.03,z+.4]],P.yellow);floorSign(label,x,z+1.1,y,3.3)}
function glowBox(w,h,d,x,y,z,color,parent=world){const m=box(w,h,d,x,y,z,color,parent);m.material=new THREE.MeshBasicMaterial({color});m.castShadow=false;return m}
function chair(x,z,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;world.add(g);box(.7,.15,.75,0,.65,0,P.coral,g);box(.7,.7,.12,0,1,-.35,P.coral,g);for(const a of [-.25,.25])for(const b of [-.25,.25])box(.04,.6,.04,a,.3,b,P.dark,g)}
function plant(x,z,y=0){const g=new THREE.Group();g.position.set(x,y,z);world.add(g);const pot=new THREE.Mesh(new THREE.CylinderGeometry(.42,.3,.65,12),mat(P.coral));pot.position.y=.33;g.add(pot);box(.06,1.5,.06,0,1.2,0,'#595959',g);for(let i=0;i<9;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.3,8,5),mat(i%2?'#7c7c7c':'#636363'));leaf.scale.set(.5,.45,1.6);leaf.position.set(Math.sin(i*2.4)*.35,1+i*.11,Math.cos(i*2.4)*.35);leaf.rotation.y=i*2.4;g.add(leaf)}}
function wallRoom(x,z,w,d,h=6,color=P.white,roof=false){box(.4,h,d,x-w/2,h/2,z,color,world,true);box(.4,h,d,x+w/2,h/2,z,color,world,true);box(w,h,.4,x,h/2,z+d/2,color,world,true);if(roof)box(w,.25,d,x,h+.125,z,color,world,true)}
function cubeBase(x,z,size=.75,kind='cube',y=0,id=null){const c=box(1,1,1,x,y+size/2,z,isLightKind(kind)?'#e4e4e4':P.yellow);c.scale.setScalar(size);c.userData={type:'cube',kind,size,vy:0,id:id||'o'+(++serial),spawn:[x,y+size/2,z],spawnSize:size};const edges=new THREE.LineSegments(new THREE.EdgesGeometry(c.geometry),new THREE.LineBasicMaterial({color:isLightKind(kind)?'#e7e7e7':'#f0f0f0'}));c.add(edges);if(isLightKind(kind)){const light=new THREE.PointLight('#eaeaea',5,12,1.5);c.add(light);c.userData.light=light;const core=new THREE.Mesh(new THREE.SphereGeometry(.26,12,8),new THREE.MeshBasicMaterial({color:'#f5f5f5'}));c.add(core);c.material=new THREE.MeshStandardMaterial({color:'#a6a6a6',emissive:'#bebebe',emissiveIntensity:.8,roughness:.4,transparent:true,opacity:.9})}else{for(let j=-1;j<=1;j++){const p=new THREE.Mesh(new THREE.CircleGeometry(.06,12),mat(P.dark));p.position.set(j*.2,0,.504);c.add(p)}}cubes.push(c);return c}
function cubeBB(c,pos=c.position,size=c.userData.size){return new THREE.Box3(new V(pos.x-size/2,pos.y-size/2,pos.z-size/2),new V(pos.x+size/2,pos.y+size/2,pos.z+size/2))}
function usableSolids(){return solids.filter(o=>o.userData.collides)}
function groundAt(x,z,from=50,withCubes=false,ignore=null){let y=-Infinity;for(const o of solids){if(!o.userData.collides)continue;const b=o.userData.bb;if(b.max.y<=from&&x>=b.min.x&&x<=b.max.x&&z>=b.min.z&&z<=b.max.z)y=Math.max(y,b.max.y)}if(withCubes)for(const c of cubes){if(c===ignore||c===held?.obj)continue;const b=cubeBB(c);if(b.max.y<=from&&x>=b.min.x&&x<=b.max.x&&z>=b.min.z&&z<=b.max.z)y=Math.max(y,b.max.y)}return y}
function obstruction(pos,size,ignore=null){const b=cubeBB({position:pos,userData:{size}},pos,size);b.expandByScalar(-.025);if(usableSolids().some(o=>b.intersectsBox(o.userData.bb)))return true;return cubes.some(c=>c!==ignore&&c!==held?.obj&&b.intersectsBox(cubeBB(c)))}
function gatePrevious(x,z,y=0,id='exit',dir=-1){const g={x,z,y,id,dir,open:false,mesh:null};for(const a of [-1,1]){box(.3,4.4,.5,x+a*1.85,y+2.2,z,P.dark,world,true);glowBox(.05,4,.08,x+a*1.66,y+2,z+.3* -dir,P.teal)}box(4,.3,.5,x,y+4.4,z,P.dark,world,true);g.mesh=box(3.4,4.2,.15,x,y+2.1,z,'#707070',world,true);g.mesh.material=new THREE.MeshStandardMaterial({color:'#707070',emissive:'#555555',emissiveIntensity:.5,transparent:true,opacity:.86});sign('EXIT / '+chapterNumber(level),x,y+5,z+.31*-dir,4,.7,'#dedede',null,dir===1?Math.PI:0);gates.push(g);return g}
function pad(x,z,min,max=5,y=0,name='重量',latch=false){const p={x,z,y,min,max,name,latch,on:false};box(2.8,.08,2.8,x,y+.04,z,P.dark);p.ring=ring(x,z,y+.06,1.1,P.yellow);floorSign(max<1?name+' ≤ '+max+' m':name+' ≥ '+min+' m',x,z+2,y,3);pads.push(p);return p}
function sensor(x,z,y=1.5){const s={pos:new V(x,y,z),on:false};box(.8,2,.5,x,1,z,P.dark);s.orb=new THREE.Mesh(new THREE.SphereGeometry(.32,20,12),new THREE.MeshBasicMaterial({color:'#707070'}));s.orb.position.copy(s.pos);world.add(s.orb);ring(x,z,0,.8,P.teal);sensors.push(s);return s}
function photoModelBasePrevious(type,ghostly=false,card=null){const g=new THREE.Group();if(type==='bridge'){box(3,.22,12,0,-.11,-6,P.white,g).userData.structSolid=true;for(let i=0;i<13;i++)box(3,.015,.025,0,.015,-i,P.blue,g);for(const x of [-1.43,1.43]){box(.08,.09,12,x,.75,-6,P.teal,g).userData.structSolid=true;for(let i=0;i<7;i++)box(.06,.72,.06,x,.36,-i*2,P.teal,g)}for(let i=1;i<4;i++){box(.07,3.15,.07,-1.48,1.57,-i*3,P.yellow,g);box(.07,3.15,.07,1.48,1.57,-i*3,P.yellow,g);box(3,.07,.07,0,3.15,-i*3,P.yellow,g)}}else if(type==='stairs'){for(let i=0;i<10;i++){box(3,(i+1)*.24,1,0,(i+1)*.12,-i-.5,i%2?P.white:'#d3d3d3',g).userData.structSolid=true;box(3,.025,.045,0,(i+1)*.24+.014,-i-.02,P.teal,g)}for(const x of [-1.55,1.55])for(let i=0;i<10;i++)box(.05,.7,.05,x,(i+1)*.24+.35,-i-.5,P.teal,g)}else{box(card?.size||1,card?.size||1,card?.size||1,0,(card?.size||1)/2,0,isLightKind(card?.kind)?P.teal:P.yellow,g)}if(ghostly)g.traverse(o=>{if(o.isMesh){o.material=new THREE.MeshBasicMaterial({color:'#cccccc',transparent:true,opacity:.32,depthWrite:false});o.castShadow=false}});return g}
const photoImages={};
function photoImage(type){if(photoImages[type])return photoImages[type];const s=new THREE.Scene();s.background=new THREE.Color('#a8a8a8');s.add(new THREE.HemisphereLight('#ffffff','#6d6d6d',3));const l=new THREE.DirectionalLight('#f1f1f1',3);l.position.set(-5,8,5);s.add(l);s.add(photoModel(type));const c=new THREE.PerspectiveCamera(50,1.25,.1,80);c.position.set(9,7,8);c.lookAt(0,.5,-5);const old=renderer.getSize(new THREE.Vector2());renderer.setSize(500,400,false);renderer.render(s,c);const url=renderer.domElement.toDataURL('image/jpeg',.8);renderer.setSize(old.x,old.y,false);photoImages[type]=url;return url}
function addCard(type,name,opts={}){const c={id:'c'+(++serial),type,name,img:opts.img||photoImage(type==='copy'?'cube':type),size:opts.size||.8,kind:opts.kind||'cube',length:opts.length||12,width:opts.width||3};cards.push(c);selected=cards.length-1;updateAlbum();return c}
function pickup(type,x,z,y=0,name='一张照片'){const g=new THREE.Group();g.position.set(x,y,z);g.userData={type:'pickup',pickup:type,name};world.add(g);box(.1,1.8,.1,-.6,.9,0,P.dark,g);box(.1,1.8,.1,.6,.9,0,P.dark,g);box(2,1.65,.15,0,1.75,0,P.white,g);if(type==='camera'){box(.9,.6,.45,0,1.8,.3,P.dark,g);const lens=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.2,18),mat(P.teal));lens.rotation.x=Math.PI/2;lens.position.set(0,1.8,.6);g.add(lens)}else{const image=new Image();const t=new THREE.Texture(image);t.colorSpace=THREE.SRGBColorSpace;image.onload=()=>t.needsUpdate=true;image.src=photoImage(type);if(image.complete)t.needsUpdate=true;const m=new THREE.Mesh(new THREE.PlaneGeometry(1.8,1.35),new THREE.MeshBasicMaterial({map:t}));m.position.set(0,1.82,.081);g.add(m)}sign(type==='camera'?'E · 领取相机':'E · '+name,x,y+3.1,z,3,.6);pickups.push(g);return g}
function makeAlignment(pos,target,reward,markerY=pos.y-EYE){const g=new THREE.Group();world.add(g);const dz=pos.z-target.z;for(let k=0;k<3;k++){const distance=dz*(.48+.24*k),ratio=distance/dz;const r=1.6*ratio;const o=new THREE.Mesh(new THREE.TorusGeometry(r,.035*ratio,8,36,Math.PI*2/3-.05),new THREE.MeshBasicMaterial({color: k===0?P.yellow:k===1?P.teal:P.coral}));o.position.set(pos.x+(target.x-pos.x)*ratio,pos.y+(target.y-pos.y)*ratio,pos.z-distance);o.rotation.z=k*Math.PI*2/3;g.add(o)}ring(pos.x,pos.z,markerY,1,P.coral);floorSign('STAND · LOOK',pos.x,pos.z+.8,markerY,2.8);align={pos,target,group:g,reward,progress:0,done:false};}
function teleportPair(a,b){function one(src,dst,side){const target=new THREE.WebGLRenderTarget(320,448);const m=new THREE.Mesh(new THREE.PlaneGeometry(3,4.2),new THREE.MeshBasicMaterial({map:target.texture,side:THREE.DoubleSide}));m.position.set(src.x,2.1,src.z);world.add(m);for(const d of [-1,1])box(.22,4.5,.4,src.x+d*1.65,2.25,src.z,P.dark,world,true);glowBox(3.5,.15,.4,src.x,4.5,src.z,P.teal);sign('FOLD / BEYOND',src.x,5,src.z+.3*side,3.5,.6,'#e8e8e8',null,side===-1?Math.PI:0);const p={src,dst,side,target,mesh:m,cam:new THREE.PerspectiveCamera()};portals.push(p)}one(a,b,1);one(b,a,-1)}
function renderPortals(){if(!portals.length)return;for(const p of portals){const dist=(player.pos.z-p.src.z)*p.side;if(dist<.15||dist>24)continue;for(const q of portals)q.mesh.visible=false;const rel=camera.position.clone().sub(new V(p.src.x,0,p.src.z));p.cam.position.set(p.dst.x+rel.x,rel.y,p.dst.z+rel.z);p.cam.rotation.set(0,p.side===1?0:Math.PI,0);const near=dist+.025,k=near/dist,rx=rel.x*p.side;p.cam.projectionMatrix.makePerspective((-1.5-rx)*k,(1.5-rx)*k,(4.2-rel.y)*k,-rel.y*k,near,140);p.cam.projectionMatrixInverse.copy(p.cam.projectionMatrix).invert();p.cam.updateMatrixWorld();renderer.setRenderTarget(p.target);renderer.render(scene,p.cam);renderer.setRenderTarget(null);for(const q of portals)q.mesh.visible=true}}
function portalCross(prev){if(portalCooldown>0)return;for(const p of portals){if((prev.z-p.src.z)*p.side>0&&(player.pos.z-p.src.z)*p.side<=0&&Math.abs(player.pos.x-p.src.x)<1.4&&player.pos.y<4.2){const delta=new V(p.dst.x-p.src.x,0,p.dst.z-p.src.z-p.side*.6);player.pos.add(delta);if(held){held.obj.position.add(delta);held.lastValid.add(delta)}portalCooldown=.7;tone(260,.4);showToast('门后的空间，比门本身要远得多。',3);return}}}
function snapshot(){history.push({pos:player.pos.toArray(),yaw:player.yaw,pitch:player.pitch,cubes:cubes.map(c=>({id:c.userData.id,size:c.userData.size,kind:c.userData.kind,pos:c.position.toArray(),spawn:c.userData.spawn,spawnSize:c.userData.spawnSize})),placed:placed.map(p=>({cardId:p.cardId,type:p.type,pos:p.pos,yaw:p.yaw,cubeId:p.cubeId,cutId:p.cutId})),flags:JSON.parse(JSON.stringify(flags))});if(history.length>16)history.shift()}
function removePlacedBase(p){if(p.group){const set=new Set();p.group.traverse(o=>set.add(o));solids=solids.filter(o=>!set.has(o));world.remove(p.group)}if(p.cubeId){const c=cubes.find(c=>c.userData.id===p.cubeId);if(c){if(held?.obj===c)held=null;world.remove(c);cubes=cubes.filter(x=>x!==c)}}placed=placed.filter(x=>x!==p)}
function restore(){const s=history.pop();if(!s){showToast('还没有可以撤销的物体操作。');return}stopPhoto();held=null;for(const p of [...placed])removePlaced(p);for(const c of cubes)world.remove(c);cubes=[];for(const d of s.cubes){const c=cube(d.pos[0],d.pos[2],d.size,d.kind,d.pos[1]-d.size/2,d.id);c.userData.spawn=d.spawn;c.userData.spawnSize=d.spawnSize}for(const p of s.placed){if(p.type==='copy')placed.push({...p});else if(p.type==='cutout')openCut(cutWalls.find(w=>w.userData.cutId===p.cutId),p.cardId);else deployStructure(p.type,new V(...p.pos),p.yaw,p.cardId)}if(level===6)homeToken=cubes.find(c=>c.userData.kind==='house')||null;player.pos.fromArray(s.pos);player.yaw=s.yaw;player.pitch=s.pitch;player.vy=0;updateAlbum();showToast('已撤销上次物体操作。',3)}
function aimTarget(){ray.setFromCamera(new THREE.Vector2(),camera);const hits=ray.intersectObjects([...cubes,...pickups,...usableSolids()],true);for(const h of hits){if(h.distance>7)return null;let o=h.object;while(o.parent&&o.parent!==world&&!o.userData.type)o=o.parent;if(o===held?.obj)continue;return o.userData.type&&(o.userData.type!=='pickup'||h.distance<3.8)?o:null}return null}
function actionBase(){if(photoMode){photoRot-=Math.PI/2;return}if(held){snapshot();held.obj.userData.vy=0;held=null;tone(190,.22);return}const o=aimTarget();if(!o){if(guideEnabled)showToast('先靠近物体，把中心准星放在它的表面。出现 E 提示后再拿取。',5);return}if(o.userData.type==='pickup'){const t=o.userData.pickup;if(t==='camera'){hasCamera=true;showToast('P 拍摄瞄准的物体；C 举照片，F 显影出可拿取的复制品。',7)}else{addCard(t,o.userData.name);showToast('照片已放入相册。C 举起；滚轮调距离；F 显影。',6)}world.remove(o);pickups=pickups.filter(p=>p!==o);chime();updateAlbum()}else{snapshot();const d=camera.position.distanceTo(o.position);held={obj:o,ratio:o.userData.size/d,distance:d,lastValid:o.position.clone()};tone(330,.15)}}
function updateHeld(){if(!held)return;const dir=camera.getWorldDirection(new V());let d=clamp(held.distance,.7,24),ok=false;for(let i=0;i<120;i++){const size=clamp(held.ratio*d,.24,4.6),p=camera.position.clone().addScaledVector(dir,d);if(Math.hypot(p.x-player.pos.x,p.z-player.pos.z)>size/2+R+.12&&!obstruction(p,size,held.obj)){held.obj.position.copy(p);held.obj.scale.setScalar(size);held.obj.userData.size=size;held.lastValid.copy(p);held.blocked=d<held.distance-.4;ok=true;break}d-=.16;if(d<.5)break}if(!ok){held.obj.position.copy(held.lastValid);held.blocked=true}}
function captureBase(){if(!hasCamera){showToast('先领取档案馆里的相机。');return}if(held||photoMode){showToast('先放下物体或照片，再拍摄。');return}const c=aimTarget();if(!c||c.userData.type!=='cube'){showToast('将准星对准三点方块或发光灯箱，按 P 拍摄。',4);return}renderer.render(scene,camera);const img=renderer.domElement.toDataURL('image/jpeg',.75);cards=cards.filter(c=>c.type!=='copy');addCard('copy',isLightKind(c.userData.kind)?'灯箱的另一份记忆':'同一件物体，第二次',{size:c.userData.size,kind:c.userData.kind,img});flash();tone(750,.12,'triangle');showToast('尺寸和种类已记进照片。C → F 可显影复制品。原物体仍然保留。',6)}
function stopPhoto(){photoMode=false;if(ghost){world.remove(ghost);ghost=null}updateAlbum()}
function togglePhoto(){if(photoMode){stopPhoto();return}if(held){showToast('先放下手里的物体。');return}const card=cards[selected];if(!card){showToast('先找一张照片。');return}if(card.type!=='copy'&&placed.some(p=>p.cardId===card.id)){showToast('这张照片已经成为实体。X 收回最近的显影，或切换其他照片。',5);return}photoMode=true;ghostValid=false;photoRot=0;ghost=photoModel(card.type,true,card);world.add(ghost);updateAlbum()}
function changeDistance(d){if(held)held.distance=clamp(held.distance+d,.7,24);else if(photoMode)photoDist=clamp(photoDist+d*.35,.5,6)}
function updateGhostBase(){if(!ghost)return;const c=cards[selected],f=new V(-Math.sin(player.yaw),0,-Math.cos(player.yaw));const x=Math.round((player.pos.x+f.x*photoDist)*2)/2,z=Math.round((player.pos.z+f.z*photoDist)*2)/2;const ground=groundAt(x,z,player.pos.y+.3);ghost.position.set(x,Number.isFinite(ground)?ground+.015:player.pos.y-EYE,z);ghost.rotation.y=Math.round(player.yaw/(Math.PI/2))*Math.PI/2+photoRot;ghost.updateMatrixWorld(true);if(c.type==='copy'){const p=new V(x,ground+c.size/2+.03,z);ghostValid=Number.isFinite(ground)&&!obstruction(p,c.size)&&Math.hypot(x-player.pos.x,z-player.pos.z)>c.size/2+R+.15&&cubes.length<8;}else{const len=c.type==='stairs'?10:12,rise=c.type==='stairs'?2.4:0,start=ghost.localToWorld(new V(0,0,-.2)),end=ghost.localToWorld(new V(0,0,-len+.2));const near=groundAt(start.x,start.z,player.pos.y+.3),far=groundAt(end.x,end.z,ghost.position.y+rise+.5);ghostValid=Number.isFinite(ground)&&Math.abs(near-ground)<.3&&Math.abs(far-ground-rise)<.32;for(const o of ghost.children){if(!o.userData.structSolid)continue;const b=new THREE.Box3().setFromObject(o);b.expandByScalar(-.055);if(usableSolids().some(s=>s.userData.bb.max.y>b.max.y+.08&&b.intersectsBox(s.userData.bb)))ghostValid=false}}ghost.traverse(o=>{if(o.isMesh)o.material.color.set(ghostValid?'#cacaca':'#cacaca')})}
function deployStructureBase(type,pos,yaw,cardId){const group=photoModel(type);group.position.copy(pos);group.rotation.y=yaw;world.add(group);group.updateMatrixWorld(true);group.traverse(o=>{if(o.userData.structSolid)addSolid(o)});const p={type,group,cardId,pos:pos.toArray(),yaw};placed.push(p);return p}
function placeBase(){if(!ghost||!photoMode)return;if(!ghostValid){showToast(photoFailureReason(),6);return}snapshot();const c=cards[selected];if(c.type==='copy'){const o=cube(ghost.position.x,ghost.position.z,c.size,c.kind,ghost.position.y);placed.push({type:'copy',cardId:c.id,cubeId:o.userData.id,pos:ghost.position.toArray(),yaw:0})}else deployStructure(c.type,ghost.position.clone(),ghost.rotation.y,c.id);stopPhoto();flash();chime();showToast('显影完成。它现在遵守这个房间的物理规则。',4)}
function recall(){const p=placed.at(-1);if(!p){showToast('没有可以收回的显影。');return}if(p.type==='cutout'){const wall=cutWalls.find(w=>w.userData.cutId===p.cutId);if(wall&&Math.abs(player.pos.x-wall.position.x)<1.8&&Math.abs(player.pos.z-wall.position.z)<.7){showToast('先走出这段墙，再收回留白。');return}}snapshot();removePlaced(p);stopPhoto();showToast('最近一次显影已收回。照片仍在相册里。',4)}
function collision(x,z,foot){for(const b of [...usableSolids().map(o=>o.userData.bb),...cubes.filter(c=>c!==held?.obj).map(c=>cubeBB(c))]){if(b.max.y<=foot+.31||b.min.y>=foot+EYE-.05)continue;if(x+R>b.min.x&&x-R<b.max.x&&z+R>b.min.z&&z-R<b.max.z)return true}return false}
function stepPlayerBase(dt){const prev=player.pos.clone();if(keys.ArrowLeft)player.yaw+=dt*1.5;if(keys.ArrowRight)player.yaw-=dt*1.5;if(keys.ArrowUp)player.pitch=clamp(player.pitch+dt,-1.35,1.3);if(keys.ArrowDown)player.pitch=clamp(player.pitch-dt,-1.35,1.3);const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0),len=Math.hypot(f,s)||1,speed=keys.ShiftLeft||keys.ShiftRight?5.4:3.7,foot=player.pos.y-EYE,dx=(-Math.sin(player.yaw)*f+Math.cos(player.yaw)*s)*speed*dt/len,dz=(-Math.cos(player.yaw)*f-Math.sin(player.yaw)*s)*speed*dt/len;if(!collision(player.pos.x+dx,player.pos.z,foot))player.pos.x+=dx;if(!collision(player.pos.x,player.pos.z+dz,foot))player.pos.z+=dz;if(keys.Space&&player.grounded){player.vy=6.1;player.grounded=false;tone(190,.08,'sine',.015)}player.vy-=15*dt;let support=-Infinity;for(const [a,b] of [[0,0],[.17,0],[-.17,0],[0,.17],[0,-.17]])support=Math.max(support,groundAt(player.pos.x+a,player.pos.z+b,foot+.315,true));const nf=foot+player.vy*dt;if(player.vy<=0&&support>=nf&&support<=foot+.315){player.pos.y=support+EYE;player.vy=0;player.grounded=true}else{if(player.vy>0){for(const b of [...usableSolids().map(o=>o.userData.bb),...cubes.filter(c=>c!==held?.obj).map(c=>cubeBB(c))])if(b.min.y>=player.pos.y-.05&&b.min.y<player.pos.y+player.vy*dt&&player.pos.x+R>b.min.x&&player.pos.x-R<b.max.x&&player.pos.z+R>b.min.z&&player.pos.z-R<b.max.z){player.vy=0;break}}player.pos.y+=player.vy*dt;player.grounded=false}portalCross(prev);if(player.pos.y<-8)respawn();syncCamera()}
function respawn(){seated=null;falls++;player.pos.copy(checkpoint);player.vy=0;player.yaw=0;player.pitch=-.03;if(held){held.obj.position.fromArray(held.obj.userData.spawn);held.obj.userData.size=held.obj.userData.spawnSize;held.obj.scale.setScalar(held.obj.userData.size);held=null}stopPhoto();showToast('已回到最近的观察点。已放置的物体和照片保留。',4)}
function stepCubes(dt){for(const c of cubes){const u=c.userData;if(u.light){u.light.distance=3+u.size*5.7;u.light.intensity=2+u.size*5}if(c===held?.obj)continue;const foot=c.position.y-u.size/2;u.vy-=13*dt;let support=-Infinity;for(const [x,z] of [[0,0],[-.3,-.3],[.3,.3],[-.3,.3],[.3,-.3]])support=Math.max(support,groundAt(c.position.x+x*u.size,c.position.z+z*u.size,foot+.06));if(support>=foot+u.vy*dt&&support<=foot+.07){c.position.y=support+u.size/2;u.vy=0}else c.position.y+=u.vy*dt;if(c.position.y<-12){c.position.fromArray(u.spawn);u.size=u.spawnSize;c.scale.setScalar(u.size);if(!Number.isFinite(groundAt(c.position.x,c.position.z,c.position.y+1))){c.position.set(checkpoint.x+1.7,checkpoint.y-EYE+u.size/2+.1,checkpoint.z)}u.vy=0;showToast('掉落的物体已回到安全位置。')}}}
function updatePads(){for(const p of pads){const ok=cubes.some(c=>c!==held?.obj&&c.userData.size>=p.min-.01&&c.userData.size<=p.max+.01&&Math.abs(c.position.x-p.x)<1&&Math.abs(c.position.z-p.z)<1&&Math.abs(c.position.y-c.userData.size/2-p.y)<.15);if(ok&&!p.on)tone(560,.3);p.on=p.latch?p.on||ok:ok;p.ring.material.color.set(p.on?'#d1d1d1':P.yellow)}}
function updateSensors(){for(const s of sensors){s.on=cubes.some(c=>isLightKind(c.userData.kind)&&c!==held?.obj&&c.position.distanceTo(s.pos)<3+c.userData.size*5.7);s.orb.material.color.set(s.on?'#eeeeee':'#666666')}}
function updateAlignment(dt,enabled=true){if(!align||align.done)return;const near=player.pos.distanceTo(align.pos)<1,dir=camera.getWorldDirection(new V()),goal=align.target.clone().sub(player.pos).normalize(),dot=dir.dot(goal);if(enabled&&near&&dot>.994){align.progress+=dt;$('focusBar').hidden=false;$('focusFill').style.width=Math.min(100,align.progress/1.2*100)+'%';if(align.progress>=1.2){align.done=true;align.group.visible=false;flags.aligned=true;align.reward();chime();flash();$('focusBar').hidden=true}}else{align.progress=Math.max(0,align.progress-dt*2);$('focusBar').hidden=!(enabled&&near);$('focusFill').style.width='0%'}}
function syncCamera(){camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0);camera.updateMatrixWorld(true)}
function showToast(text,d=5){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+d*1000}
function flash(){ $('flash').style.opacity='.7';setTimeout(()=>$('flash').style.opacity='0',65)}
let audioCtx,ambientGain,stepClock=0;
function ambience(dt){if(!audioCtx)return;try{if(!ambientGain){ambientGain=audioCtx.createGain();ambientGain.gain.value=0;ambientGain.connect(audioCtx.destination);for(const f of [55,110]){const o=audioCtx.createOscillator();o.frequency.value=f;o.connect(ambientGain);o.start()}}ambientGain.gain.setTargetAtTime(active&&!muted?(level===1?.009:level===4?.004:.0015):0,audioCtx.currentTime,.2);if(active&&player.grounded&&(keys.KeyW||keys.KeyS||keys.KeyA||keys.KeyD)){stepClock+=dt;if(stepClock>.45){stepClock=0;tone(level===1?92:135,.055,'triangle',level===1?.018:.024)}}else stepClock=0}catch(e){}}

function tone(freq=440,dur=.2,type='sine',gain=.045){if(muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function chime(){tone(392,.5);setTimeout(()=>tone(523,.6),130);setTimeout(()=>tone(784,.8),270)}
const chapters=[
{title:'迟到的接待处',sub:'01 / A STEP THAT WAS A PICTURE',goal:'接待台在楼上。先借一个台阶，再借整段楼梯。',intro:'欢迎来到未登记楼层。所有尺寸均以你的目光为准。',hints:['三点方块可以作为台阶。靠近按 E 拿起，平视远处，用滚轮向上或 + 放大。','把方块放在左侧高台的边缘，尺寸约 1.1–1.4 米。空格跳上方块，再跳到高台。','走到高台尽头取楼梯照片。回到大厅中央的 DEVELOP 标记，朝出口 C 举照片。','让楼梯起点搭在大厅边缘、终点搭住高处出口平台。显示“可显影”时 F 显影，再走上去。']},
{title:'你已经来过这里',sub:'02 / PLEASE LEAVE SOMETHING BEHIND',goal:'找到能在重复中留下来的东西。',intro:'这里每一盏灯，都记得你刚才经过的样子。',hints:['前面的走廊会把你送回原处。注意左侧的小尺寸圆环。','将方块缩小到 0.65 米以下，放进左侧圆环。小物体会成为空间的锚。','留下方块后，再向前走过一次循环，然后回头看。','亮起的出口在来时的方向，走廊最后方。不要继续追着向前的箭头。']},
{title:'泳池没有倒影',sub:'03 / THE CORRECT PLACE TO BE WRONG',goal:'借照片登上观测台，让分散的轮廓重新重合。',intro:'水没有保存倒影。它把倒影留在了别处。',hints:['领取右侧楼梯照片，在近岸 DEVELOP 标记朝中央高台显影。楼梯要同时搭住两端。','沿楼梯走上高台。站在深色观察圆环中心，朝远处看。','把三段彩色弧线看成一个完整的圆，保持视线一小会儿。一张新的桥照片会出现。','按 1 / 2 或 Tab 选择桥照片，在高台后缘朝出口显影。楼梯和桥可以同时存在。']},
{title:'一个人，两份重量',sub:'04 / THE ARCHIVE ACCEPTS COPIES',goal:'只有一个原件，却有两个必须同时工作的接口。',intro:'本馆不区分原件与副本。请不要因此轻视自己。',hints:['从中间的台子领取相机。P 拍摄瞄准的三点方块。','C 举起物体照片，再按 F，在空地显影出第二个可拿取的方块。','一个缩小到 0.85 米以下，放左侧接口；另一个放大到 1.8 米以上，放右侧接口。','两个接口必须同时保持亮起。中间楼梯接通后，沿楼梯走进上层出口。']},
{title:'请在转身后施工',sub:'05 / A GARDEN BEHIND A SMALL DOOR',goal:'把光带过折叠门，让没有被注视的路完成施工。',intro:'门只有一米远，门后的花园却不在这栋楼里。',hints:['拿起发光灯箱，带着它穿过正前方的青色门。另一边是一座更大的花园。','在花园近岸把灯箱放大，放在断崖边。尺寸约 2 米以上，光就能碰到对面的接收器。','对岸接收器亮起后，背对断崖约一秒。桥只能在无人注视时归位。','转回来查看桥。走过它，进入花园尽头的门。灯箱若丢在门外，可以原路返回。']},
{title:'归档之前',sub:'06 / NOTHING HERE HAS ONLY ONE PURPOSE',goal:'稳定地址、保存副本，把光与重量送到另一岸。',intro:'最后一个房间，由你之前相信过的所有例外构成。',hints:['先给三点方块拍照。再把原件缩小到 0.7 米以下，留在近岸的锚点上。否则走到桥中间会回到起点。','在近岸显影桥照片。切换到物体照片，显影副本，再把副本带到对岸。','把副本放大到至少 1.8 米，留在右侧重量接口上。原件仍要守住近岸锚点。','再把灯箱带到对岸并放大，让左侧的光接收器亮起。也可以拍下灯箱，把它的副本带过去。','三处条件都成立时，上层楼梯会接通。站到最上方观察点，拼好最后一个圆，出口才会出现。']}
];
function setupLightLegacyPrevious(theme='day',cx=0){const warm=theme==='back';scene.background=new THREE.Color(warm?'#292929':theme==='night'?'#303030':'#b6b6b6');scene.fog=new THREE.Fog(scene.background,theme==='back'?28:48,130);world.add(new THREE.HemisphereLight(warm?'#f2f2f2':'#f8f8f8',warm?'#666666':'#666666',warm?1.7:2));const s=new THREE.DirectionalLight(warm?'#f0f0f0':'#eaeaea',warm?1.2:2.5);s.position.set(cx-12,25,12);s.target.position.set(cx,0,-8);world.add(s.target);s.castShadow=true;s.shadow.mapSize.set(2048,2048);Object.assign(s.shadow.camera,{left:-26,right:26,top:30,bottom:-30,near:1,far:90});s.shadow.camera.updateProjectionMatrix();s.shadow.normalBias=.035;world.add(s);if(theme!=='back'){const moon=new THREE.Mesh(new THREE.SphereGeometry(5,24,16),new THREE.MeshBasicMaterial({color:theme==='night'?'#e0e0e0':'#f0f0f0'}));moon.position.set(cx-34,30,-70);world.add(moon);for(let i=0;i<13;i++){const h=4+(i*7)%17;box(3+i%3,h,5,cx+(i%2?1:-1)*(19+(i*5)%20),-8+h/2,-20-i*5,i%3===0?P.coral:P.blue)}}}
function waterPrevious(w,d,x,z,y=-.85){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.ShaderMaterial({transparent:true,uniforms:{time:{value:0}},vertexShader:'varying vec2 v; void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v; uniform float time; void main(){float a=sin(v.x*150.+time*.7)*sin(v.y*190.-time*.5);float b=sin(v.x*52.+v.y*70.+time*.3);vec3 col=mix(vec3(.10,.39,.42),vec3(.35,.68,.65),a*.15+b*.08+.35);gl_FragColor=vec4(col,.87);}'}));m.rotation.x=-Math.PI/2;m.position.set(x,y,z);world.add(m);decorAnim.push(m)}
function buildReception(){setupLight();floor(20,24,0,1,0,'@tile');wallRoom(0,1,20,24,8,P.white);for(const x of [-8.5,8.5])for(const z of [-8,1,10])box(.55,9,.55,x,4.5,z,P.coral);floor(5,6,-5,-7,2.2,P.white);box(5,.5,2,-5,2.8,-9,P.dark);pickup('stairs',-5,-9.5,2.2,'一段楼梯');cube(-4,3,.65);floorSign('借我一个台阶',-5,0,0,4);sign('RECEPTION / ABOVE',-5,5.7,-10,5,.8);dock(0,-10);floor(10,6,0,-22.75,2.4,'@tile');const g=gate(0,-24,2.4);g.open=true;chair(6,6,.5);chair(7.5,6,.5);plant(7,1);plant(-8,9);const r=new THREE.Mesh(new THREE.TorusGeometry(3.5,.12,10,70),mat(P.teal));r.position.set(0,8,-1);r.rotation.x=Math.PI/2;world.add(r);sign('DEPARTMENT OF UNMEASURED DISTANCES',0,7,-10.8,13,1);flags.hint=0;}
let backSeal,loopText;
function buildBackrooms(){setupLight('back');floor(12,42,0,-5,0,'@carpet');wallRoom(0,-5,12,42,4.3,'@wall',true);for(let z=11;z>=-22;z-=5){for(const x of [-4.7,4.7]){box(.55,4.2,.65,x,2.1,z,'@wall',world,true);box(1,2.1,.3,x,1.05,z-1.7,'@wall')}glowBox(1.7,.045,.75,0,4.2,z,'#f1f1f1');if(z>-15){const l=new THREE.PointLight('#f0f0f0',7,9,2);l.position.set(0,3.8,z);world.add(l)}floorSign('↑',0,z,0,1.2)}cube(2.5,5,.95);pad(-3,-7,.24,.65,0,'锚点',true);sign('先留下你的一部分。然后回头。',0,2.4,-18.8,8,1,'#383838','#bcbcbc');loopText=sign('PASSAGE / 01',0,3.1,-12,5,.65);backSeal=box(4.1,4.3,.2,0,2.15,13.5,'@wall',world,true);gate(0,14,0,'exit',1);flags.loops=0;flags.seenDoor=false;chair(-4,2,1.6);box(1.4,1.2,.6,4, .6,-4,P.dark);sign('没有第八次。',-4,2,2,2,.6,'#383838');}
function buildPoolPrevious(){setupLight();water(65,65,0,-13);floor(16,12,0,7,0,'@tile');floor(8,6,0,-10.75,2.4,'@tile');floor(14,8,0,-28.5,2.4,'@tile');for(const x of [-8,8])for(let z=8;z>=-33;z-=7){box(1.1,8,1.1,x,2.5,z,'@tile');box(2,.3,2,x,6.65,z,P.white)}for(const x of [-5,5]){box(.2,2,10,x,1,7,P.blue);glowBox(.03,.05,9,x-.12,1.9,7,P.teal)}pickup('stairs',4,8,0,'水面上的楼梯');dock(0,2);dock(0,-13,2.4,'SECOND EXPOSURE');makeAlignment(new V(0,4.05,-10),new V(0,4.05,-25),()=>{addCard('bridge','从轮廓里借来的桥');showToast('分散的轮廓，变成了一张桥照片。切换到它，继续向前。',6)});const g=gate(0,-30,2.4);g.open=true;sign('THE POOL HAS MISPLACED ITS REFLECTION',0,7,-31,12,1);plant(-5,10);}
let archiveStairs=[];
function builtStair(x,z,y=0){const group=photoModel('stairs');group.position.set(x,y,z);world.add(group);const bodies=[];group.traverse(o=>{if(o.userData.structSolid){addSolid(o);bodies.push(o)}});return {group,bodies}}
function toggleBuilt(item,on){item.group.visible=on;for(const b of item.bodies)b.userData.collides=on}
function buildArchive(){setupLight('night');floor(20,30,0,0,0,'@tile');wallRoom(0,0,20,30,12,P.dark);for(const x of [-7,7]){for(let z=8;z>=-12;z-=4){box(2.5,6,1.4,x,3,z,P.dark,world,true);for(let j=1;j<=5;j++){box(2.6,.1,1.5,x,j, z,P.teal);for(let i=0;i<6;i++)box(.23,.7,1,x-1+i*.38,j+.38,z,[P.coral,P.white,P.blue,P.yellow][(i+j)%4])}}}cube(0,4,.9);pickup('camera',0,9);pad(-3,0,.24,.85,0,'细接口');pad(3,-4,1.8,4.6,0,'重接口');archiveStairs=builtStair(0,-7);toggleBuilt(archiveStairs,false);floor(8,7,0,-20.25,2.4,'@tile');gate(0,-22,2.4);sign('ONE ORIGINAL / TWO IDENTITIES',0,8,-13,11,1);line([[-3,.02,0],[-3,.02,-6],[0,.02,-6],[3,.02,-6],[3,.02,-4]],P.teal);}
let quantumPieces=[],quantumProgress=0;
function buildGarden(){setupLight('night',36);floor(12,20,0,2,0,'@tile');wallRoom(0,2,12,20,7,P.blue);box(4,7,.4,-4,3.5,-8,P.blue,world,true);box(4,7,.4,4,3.5,-8,P.blue,world,true);cube(2,5,.55,'lamp');sign('把光带进去。',0,5,-7.7,4,.65,'#e8e8e8');teleportPair({x:0,z:-8},{x:36,z:7});floor(14,12,36,7,0,'@tile');floor(14,14,36,-16,0,'@tile');water(25,24,36,-5,-1.1);for(const x of [29,43])for(const z of [10,-13,-20]){box(.6,8,.6,x,4,z,P.dark);plant(x,z);glowBox(.08,6,.08,x+.35,3,z,P.teal)}sensor(36,-11,1.2);gate(36,-20);quantumPieces=[];for(let i=0;i<5;i++){const m=box(3,.3,2,49,-.15, -i*2,P.white,world,true);m.userData.collides=false;quantumPieces.push(m);glowBox(3.03,.03,.04,0,.165,0,P.teal,m)}quantumProgress=0;flags.bridgeBuilt=false;floorSign('只在无人注视时施工',36,3,0,5);sign('THE GARDEN IS NOT BEHIND THIS WALL',36,6,-22,12,1,'#e1e1e1');}
let finalStairs;
function buildFinal(){setupLight('day');floor(18,12,0,7,0,'@carpet');floor(18,16,0,-17,0,'@tile');floor(8,7,0,-29.75,2.4,'@tile');water(32,25,0,-8,-1);for(const x of [-9,9]){box(.4,6,12,x,3,7,'@wall');for(let z=-12;z>=-29;z-=6)box(.6,9,.6,x,4.5,z,P.coral)}cube(-2,8,.8);cube(3,8,.55,'lamp');hasCamera=true;addCard('bridge','从泳池带来的桥');pad(-4,5,.24,.7,0,'地址锚点');pad(4,-15,1.8,4.6,0,'重量');sensor(-4,-15,1.2);dock(0,2);finalStairs=builtStair(0,-17);toggleBuilt(finalStairs,false);gate(0,-32,2.4);makeAlignment(new V(0,4.05,-28.5),new V(0,4.05,-37),()=>{flags.finalDoor=true;showToast('所有例外，现在指向同一个出口。',6)});flags.finalDoor=false;flags.drift=0;sign('KEEP AN ORIGINAL. TAKE A POSSIBILITY.',0,6,-1,13,1);floorSign('这里需要一份留下的原件',-4,8,0,4);plant(-7,10);plant(7,-22);line([[4,.02,-15],[4,.02,-17],[0,.02,-17],[-4,.02,-17],[-4,.02,-15]],P.teal);}
function disposeWorld(){if(!world)return;for(const w of monoWater)w.userData.reflection?.dispose();for(const p of portals)p.target.dispose();world.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material&&!mats.has([...mats.entries()].find(([k,v])=>v===o.material)?.[0])){if(o.material.map&&!Object.values(photoImages).includes(o.material.map))o.material.map.dispose();o.material.dispose()}});scene.remove(world)}
function loadLevel(n){stopPhoto();disposeWorld();level=n;world=new THREE.Group();scene.add(world);solids=[];cubes=[];pickups=[];cards=[];placed=[];gates=[];pads=[];sensors=[];portals=[];decorAnim=[];held=null;ghost=null;selected=0;photoMode=false;ghostValid=false;photoDist=2;photoRot=0;hasCamera=true;align=null;flags={};history=[];portalCooldown=0;resetExpansion();checkpoint.set(0,EYE,10);[buildReception,buildBackrooms,buildPool,buildArchive,buildGarden,buildFinal,buildHouseWave,buildHedgeMemory,buildChoir,buildShadowField,buildMoonRoad,buildPractice][n]();enhanceScene();player.pos.copy(checkpoint);player.yaw=0;player.pitch=-.03;player.vy=0;player.grounded=true;world.updateMatrixWorld(true);for(const o of solids)refresh(o);syncCamera();$('chapterNo').textContent=chapters[n].sub;$('chapterTitle').textContent=chapterNumber(n)+' / '+chapters[n].title;$('objective').textContent=chapters[n].goal;$('focusBar').hidden=true;updateAlbum();resetGuideSession();resetPracticeUI();}
function loopBack(amount){player.pos.z+=amount;if(held){held.obj.position.z+=amount;held.lastValid.z+=amount}portalCooldown=.5;tone(110,.22);}
function tickLevel(dt){if(level===0){$('objective').textContent=cards.length?'把楼梯照片接到大厅尽头的高处出口。':chapters[0].goal;}if(level===1){if(player.pos.z<-20){loopBack(28);flags.loops++;world.remove(loopText);loopText=sign('PASSAGE / '+String(flags.loops+1).padStart(2,'0'),0,3.1,-12,5,.65);showToast(flags.loops===1?'又是这盏灯。你刚刚走过的距离去哪了？':'走廊重复了 '+flags.loops+' 次。它等待你留下一个锚。',5)}if(pads[0].on&&flags.loops>0&&!flags.seenDoor){const toEntrance=new V(0,2,14).sub(player.pos).normalize();if(camera.getWorldDirection(new V()).dot(toEntrance)<.1){flags.seenDoor=true;showToast('身后的荧光灯，换了一种声音。',5)}}solidOn(backSeal,!flags.seenDoor);gates[0].open=flags.seenDoor;$('objective').textContent=flags.seenDoor?'回头。出口终于记起了自己的位置。':pads[0].on?'锚已留下。走到走廊尽头，再回望来路。':chapters[1].goal;}
if(level===2){if(player.pos.z<-8&&player.pos.z>-13.6&&player.pos.y>3.9){checkpoint.set(0,4.05,-10)}updateAlignment(dt);$('objective').textContent=align.done?'在高台后缘显影桥照片，走向出口。':cards.length?'登上观察台，从红圈看向远处的三段弧线。':chapters[2].goal;}
if(level===3){const on=pads.every(p=>p.on);toggleBuilt(archiveStairs,on);gates[0].open=on;$('objective').textContent='细接口 '+(pads[0].on?'✓':'○')+'　重接口 '+(pads[1].on?'✓':'○')+'　· 两者需要同时保持接通';}
if(level===4){if(player.pos.x>25){checkpoint.set(36,EYE,10)}const target=new V(36,1,-4).sub(player.pos).normalize();if(sensors[0].on&&camera.getWorldDirection(new V()).dot(target)<.15&&player.pos.x>25){quantumProgress+=dt;if(quantumProgress>.8&&!flags.bridgeBuilt){flags.bridgeBuilt=true;showToast('身后传来一声轻轻的落地声。',5);chime()}}else quantumProgress=0;for(let i=0;i<quantumPieces.length;i++){const o=quantumPieces[i];o.position.x=flags.bridgeBuilt?36:49;o.userData.collides=flags.bridgeBuilt;refresh(o)}gates[0].open=flags.bridgeBuilt;$('objective').textContent=flags.bridgeBuilt?'路已归位。穿过花园。':sensors[0].on?'接收器亮了。给施工留一点不被注视的时间。':player.pos.x>25?'放大灯箱，让它的光碰到对岸接收器。':'拿着灯箱，穿过白色折叠门。';}
if(level===5){if(player.pos.z<-4&&player.pos.z>-8&&!pads[0].on&&portalCooldown<=0){loopBack(14);flags.drift++;showToast('地址未稳定。需要有一个小物体留在近岸锚点。',6)}const power=pads.every(p=>p.on)&&sensors[0].on;toggleBuilt(finalStairs,power);updateAlignment(dt,power);gates[0].open=!!flags.finalDoor;$('objective').textContent=flags.finalDoor?'最后的出口已经出现。':`地址 ${pads[0].on?'✓':'○'}　重量 ${pads[1].on?'✓':'○'}　光 ${sensors[0].on?'✓':'○'}　视点 ${align.done?'✓':'○'}`;}
if(level>=6&&level<=10)tickExpansion(dt);if(level===11)tickPractice(dt);
for(const g of gates){g.mesh.userData.collides=!g.open;g.mesh.position.y=THREE.MathUtils.lerp(g.mesh.position.y,g.y+(g.open?6.8:2.1),dt*4);refresh(g.mesh);if(g.open&&Math.abs(player.pos.x-g.x)<1.48&&Math.abs(player.pos.y-EYE-g.y)<.8&&(player.pos.z-g.z)*g.dir>-.32&&Math.abs(player.pos.z-g.z)<2.5){complete();return}}}
/* EXPANSION */
/* GUIDANCE */
/* PRACTICE */
/* ART */
/* MONOCHROME */
/* CAMPAIGN */
function updateAlbumBase(){const c=cards[selected];$('photo').hidden=!c;$('photo').classList.toggle('ready',photoMode);if(c){$('photoImage').src=c.img;$('photoCaption').textContent=c.name;$('photoNote').textContent=c.type==='copy'?'物体快照 · '+c.size.toFixed(2)+' m · '+(isLightKind(c.kind)?'灯箱':'方块'):c.type==='stairs'?'楼梯 · 高差 2.4 m · 长 10 m':'桥 · 同高平台 · 长 12 m';}$('album').replaceChildren();cards.forEach((card,i)=>{const b=document.createElement('button');b.className=i===selected?'selected':'';b.textContent=(i+1)+' '+(card.type==='copy'?'物体':card.type==='stairs'?'楼梯':'桥')+(placed.some(p=>p.cardId===card.id)&&card.type!=='copy'?' ↗':'');b.onclick=()=>selectCard(i);$('album').append(b)});$('cameraBadge').textContent=hasCamera?'P 物体快照':'相机尚未领取';}
function selectCard(i){if(!cards[i])return;const was=photoMode;stopPhoto();selected=i;updateAlbum();if(was)togglePhoto()}
function promptBase(){let msg='',o=null;if(photoMode)msg=ghostValid?'✓ 可显影　F / 左键':'移动 / 滚轮 · 调整落点　Q / E · 旋转';else if(held)msg='E 放下 · '+held.obj.userData.size.toFixed(2)+' m'+(isLightKind(held.obj.userData.kind)?' · 光距 '+(3+held.obj.userData.size*5.7).toFixed(1)+' m':'');else{o=aimTarget();if(o)msg=o.userData.type==='pickup'?'E · '+(o.userData.pickup==='camera'?'领取相机':'收下照片'):'E 拿起'+(hasCamera?'　P 拍摄':'');}if(align&&!align.done&&player.pos.distanceTo(align.pos)<1.3&&!msg)msg='让三段弧线重合，保持视线';$('prompt').hidden=!msg;$('prompt').textContent=msg;$('cross').classList.toggle('active',!!o||!!held||photoMode);$('state').textContent=photoMode?'显影预览 · '+(ghostValid?'落点有效':'请调整'):held?'滚轮推远放大 / 拉近缩小':'Z 撤销操作 · X 收回显影';}
function clearKeys(){for(const k in keys)keys[k]=false}
function lock(){try{const p=renderer.domElement.requestPointerLock();if(p?.catch)p.catch(()=>{})}catch(e){}}
function startGame(n=CAMPAIGN[0]){loadLevel(n);begun=true;active=true;won=false;elapsed=0;falls=0;$('start').hidden=true;$('pause').hidden=true;$('win').hidden=true;$('hud').hidden=false;$('resumeBtn').textContent='继续探索';clearKeys();lock();showToast(chapters[n].intro,6);tone(294,.5)}
function pauseGame(){if(!begun||won)return;active=false;$('pause').hidden=false;clearKeys();if(document.pointerLockElement)document.exitPointerLock()}
function resume(){if(!begun){$('pause').hidden=true;return}active=true;$('pause').hidden=true;clearKeys();lock()}
function renderLevelSelect(){$('levelSelect').replaceChildren();CAMPAIGN.forEach((raw,index)=>{const c=chapters[raw],b=document.createElement('button');b.innerHTML='<span class="chapterIndex">'+chapterNumber(raw)+'</span><span><strong>'+c.title+'</strong><small>'+c.mechanics+'</small></span>';b.onclick=()=>startGame(raw);$('levelSelect').append(b)});$('continueBtn').textContent='继续第 '+String(unlocked+1).padStart(2,'0')+' 章'}
function toMenu(){active=false;begun=false;$('start').hidden=false;$('pause').hidden=true;$('win').hidden=true;$('hud').hidden=true;clearKeys();if(document.pointerLockElement)document.exitPointerLock();renderLevelSelect()}
function complete(){const ordinal=CAMPAIGN.indexOf(level);if(level===PRACTICE_LEVEL)practiceFinished=true;if(ordinal>=0&&ordinal<CAMPAIGN.length-1){const next=ordinal+1;unlocked=Math.max(unlocked,next);try{localStorage.setItem('borrowed-distance-iv',String(unlocked))}catch(e){}flash();loadLevel(CAMPAIGN[next]);chime();showToast(chapters[level].intro,7)}else{won=true;active=false;$('hud').hidden=true;$('win').hidden=false;$('winStats').textContent='六个空间已连接。空间接住了你 '+falls+' 次。';if(document.pointerLockElement)document.exitPointerLock();chime()}}

$('researchBtn').onclick=()=>{$('research').hidden=false};$('closeResearch').onclick=()=>{$('research').hidden=true};
$('startBtn').onclick=()=>startGame(CAMPAIGN[0]);$('continueBtn').onclick=()=>startGame(CAMPAIGN[unlocked]);$('helpBtn').onclick=()=>{$('pause').hidden=false;$('resumeBtn').textContent='返回'};$('resumeBtn').onclick=resume;$('pauseBtn').onclick=pauseGame;$('hintBtn').onclick=hint;$('menuBtn').onclick=toMenu;$('replayBtn').onclick=()=>startGame(CAMPAIGN[0]);$('endMenuBtn').onclick=toMenu;$('sensitivity').oninput=e=>sensitivity=+e.target.value;$('fov').oninput=e=>{camera.fov=+e.target.value;camera.updateProjectionMatrix()};$('soundBtn').onclick=()=>{muted=!muted;$('soundBtn').textContent='声音：'+(muted?'关闭':'开启')};$('qualityBtn').onclick=()=>{highQuality=!highQuality;renderer.shadowMap.enabled=highQuality;renderer.setPixelRatio(highQuality?Math.min(devicePixelRatio,1.5):1);$('qualityBtn').textContent='画质：'+(highQuality?'精细':'流畅');if(!highQuality)for(const p of portals)p.mesh.material.color.set('#cbcbcb');else for(const p of portals)p.mesh.material.color.set('#ffffff')};
let dragging=false;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&active)e.preventDefault();if(e.code==='KeyG'&&!e.repeat){setGuidance(!guideEnabled,true);return}if(guideHintOpen){if(e.code==='Escape'||e.code==='KeyH')closeGuideHint();return}if(e.code==='Escape'){if(active)pauseGame();else if(begun&&!won)resume();return}if(!active)return;keys[e.code]=true;if(e.repeat)return;if(/^Digit[1-5]$/.test(e.code)){selectCard(+e.code.slice(-1)-1);return}switch(e.code){case'KeyE':action();break;case'KeyC':togglePhoto();break;case'KeyF':if(photoMode)place();else enterHouse();break;case'KeyV':toggleEcho();break;case'KeyP':capture();break;case'KeyQ':if(photoMode)photoRot+=Math.PI/2;break;case'KeyX':recall();break;case'KeyZ':restore();break;case'KeyR':loadLevel(level);showToast('本章已重置。');break;case'KeyH':hint();break;case'Tab':if(cards.length)selectCard((selected+1)%cards.length);break;case'Equal':case'NumpadAdd':changeDistance(1);break;case'Minus':case'NumpadSubtract':changeDistance(-1);break}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{clearKeys();if(active)pauseGame()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pauseGame()});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&active)pauseGame()});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('mousedown',e=>{if(!active)return;if(e.button===2){dragging=true;return}if(e.button===0){if(photoMode)place();else action()}});window.addEventListener('mouseup',()=>dragging=false);window.addEventListener('mousemove',e=>{if(!active||(!document.pointerLockElement&&!dragging))return;player.yaw-=e.movementX*.0022*sensitivity;player.pitch=clamp(player.pitch-e.movementY*.0022*sensitivity,-1.35,1.3)});window.addEventListener('wheel',e=>{if(active&&(held||photoMode)){e.preventDefault();changeDistance(-Math.sign(e.deltaY)*.8)}},{passive:false});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.033);last=now;ambience(dt);if(active){elapsed+=dt;portalCooldown=Math.max(0,portalCooldown-dt);stepPlayer(dt);if(held)updateHeld();stepCubes(dt);world.updateMatrixWorld(true);if(ghost)updateGhost();updatePads();updateSensors();tickLevel(dt);if(frame%4===0){prompt();renderGuidance();}if(now>toastUntil)$('toast').classList.remove('show');}for(const o of decorAnim)o.material.uniforms.time.value=now/1000;if(frame++%(highQuality?3:15)===0)renderPortals();updateMonochrome(now);renderer.render(scene,camera)}
initGuidance();initPractice();loadLevel(2);player.pos.set(12,6.8,17);camera.position.copy(player.pos);camera.lookAt(0,4,-10);player.yaw=camera.rotation.y;player.pitch=camera.rotation.x;syncCamera();renderLevelSelect();$('loading').hidden=true;requestAnimationFrame(tick);
