const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]);for(const s of scripts)new vm.Script(s);
assert(!/<script[^>]+src=|<link[^>]+href=/.test(html),'External asset link');assert(!/fetch\(|import\s*\(|https?:\/\//.test(scripts[2]),'Game requests external resource');
const elements=new Map();const drawing=new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});function el(id){if(!elements.has(id))elements.set(id,{hidden:false,textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(k,v){this[k]=v},replaceChildren(){},append(){},getContext(){return drawing},toDataURL(){return 'data:image/jpeg;base64,TEST'},requestPointerLock(){}});return elements.get(id)}
const ctx={console,performance:{now:()=>0},devicePixelRatio:1,innerWidth:1280,innerHeight:800,setTimeout:f=>0,requestAnimationFrame(){},window:{addEventListener(){}},document:{getElementById:el,createElement:t=>el('generated'+Math.random()),addEventListener(){},pointerLockElement:null},localStorage:{values:{},getItem(k){return this.values[k]??null},setItem(k,v){this.values[k]=v},removeItem(k){delete this.values[k]}},Image:class{constructor(){this.complete=true}},};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(scripts[1],ctx);vm.runInContext(`THREE.WebGLRenderer=class{constructor(){this.domElement=document.getElementById('world');this.shadowMap={};}setPixelRatio(){}setSize(){}setRenderTarget(){}render(){}getSize(v){return v.set(1280,800)}}`,ctx);vm.runInContext(scripts[2],ctx);
const run=c=>vm.runInContext(c,ctx);function test(n,c){assert(run(c),n);console.log('PASS',n)}
run(`function settle(n=150){for(let i=0;i<n;i++){stepCubes(1/60);updatePads();updateSensors();world.updateMatrixWorld(true)}}function aimAt(v){camera.position.copy(player.pos);camera.lookAt(v);camera.updateMatrixWorld(true)}function at(x,z,y=EYE){player.pos.set(x,y,z);player.yaw=0;player.pitch=0;player.vy=0;player.grounded=true;syncCamera()}function walk(frames,key='KeyW'){keys[key]=true;for(let i=0;i<frames;i++){stepPlayer(1/60);world.updateMatrixWorld(true)}keys[key]=false;}function ghostAt(type,x,z,y=EYE){if(photoMode)stopPhoto();selected=cards.findIndex(c=>c.type===type);at(x,z,y);photoDist=2;togglePhoto();updateGhost();return ghostValid;}`);
test('Pool first photo staircase spans actual gap',`(()=>{loadLevel(2);addCard('stairs','test');if(!ghostAt('stairs',0,4))return false;place();at(0,4);walk(230);return player.pos.z<-10&&player.pos.y>4})()`);
test('Anamorphic ring only resolves at intended viewpoint',`(()=>{at(3,-10,4.05);aimAt(align.target);updateAlignment(2);if(align.done)return false;at(0,-10,4.05);aimAt(align.target);updateAlignment(1.3);return align.done&&cards.some(c=>c.type==='bridge')})()`);
test('Second pool photo coexists with first structure',`(()=>{if(!ghostAt('bridge',0,-11,4.05))return false;place();at(0,-11,4.05);walk(300);return placed.length===2&&player.pos.z<-29&&player.pos.y>4})()`);
test('Tiny house is enterable only after perspective enlargement',`(()=>{loadLevel(6);at(0,5);aimAt(homeToken.position);enterHouse();if(flags.enteredHome)return false;homeToken.userData.size=2.8;homeToken.scale.setScalar(2.8);homeToken.position.set(0,1.4,1);world.updateMatrixWorld(true);at(0,5);aimAt(homeToken.position);enterHouse();return flags.enteredHome&&player.pos.x===38&&checkpoint.x===38})()`);
test('Photo carries light into the enlarged house',`(()=>{addCard('copy','灯',{kind:'lamp',size:.55});if(!ghostAt('copy',41,-2))return false;place();settle();tickLevel(.1);return gates[0].open&&cubes.some(c=>c.userData.kind==='lamp'&&c.position.x===41)})()`);
test('Interior return restores position outside the house',`(()=>{leaveHouse();return player.pos.x===0&&player.pos.z===5})()`);
run(`function cutAt(index,x,z,y=EYE){stopPhoto();at(x,z,y);selected=cards.findIndex(c=>c.type==='cutout');togglePhoto();aimAt(new V(cutWalls[index].position.x,1.6,cutWalls[index].position.z));updateGhost();if(!ghostValid)return false;place();return !cutWalls[index].userData.collides;}`);
test('Negative photo removes a real section of concrete wall',`(()=>{loadLevel(7);const anchor=cubes[0];anchor.userData.size=.5;anchor.scale.setScalar(.5);anchor.position.set(0,.25,7);settle();return cutAt(0,-4,4)&&placed[0].type==='cutout'&&!cutWalls[0].userData.foliage.visible})()`);
test('Player walks through negative aperture and advances maze',`(()=>{at(-4,4);walk(110);tickLevel(.1);return flags.mazeStage===1&&player.pos.z<-2})()`);
test('Recalled negative restores the wall and becomes reusable',`(()=>{recall();return cutWalls[0].userData.collides&&cutWalls[0].userData.foliage.visible&&placed.length===0})()`);
test('Second negative cut and correct branch resolve maze',`(()=>{if(!cutAt(5,4,-8))return false;at(4,-8);walk(110);tickLevel(.1);return flags.mazeStage===2&&gates[0].open})()`);
test('Wrong maze branch loops without losing the negative',`(()=>{loadLevel(7);pads[0].on=true;at(0,-3);tickLevel(.1);return player.pos.z===13&&flags.mazeLoops===1&&cards[0].type==='cutout'})()`);
test('Recall rejects restoring a wall through the player',`(()=>{cutAt(0,-4,4);at(-4,1);recall();return placed.length===1&&!cutWalls[0].userData.collides})()`);
test('Undo round-trips negative cuts with original identity',`(()=>{at(-4,-3);recall();restore();return placed.length===1&&placed[0].cutId===cutWalls[0].userData.cutId&&!cutWalls[0].userData.collides})()`);
test('Echo is reset when moving to another chapter',`(()=>{loadLevel(9);return !echoModel&&!echoState&&!echoRecord})()`);
test('Object height changes calculated projected shadow length',`(()=>{const c=shadowCaster;c.position.set(0,.4,2.5);tickLevel(.1);const small=shadowLength;c.userData.size=2.8;c.scale.setScalar(2.8);c.position.y=1.4;settle();tickLevel(.1);return shadowLength>13&&shadowLength>small*3&&shadowMesh.visible})()`);
test('Photographing shadow captures length rather than a generic bridge',`(()=>{at(4,0);aimAt(new V(0,.035,-3));world.updateMatrixWorld(true);capture();return cards.some(c=>c.type==='shadow'&&c.length>13&&c.length<=14)})()`);
test('Shadow photo develops into a traversable bridge',`(()=>{if(!ghostAt('shadow',0,4))return false;place();at(0,0.6);walk(260);return player.pos.z<-15&&player.pos.y>1.5&&placed.some(p=>p.type==='shadow')})()`);
test('Retrieving a shadow road restores the gap',`(()=>{recall();return groundAt(0,-4)===-Infinity})()`);
test('Road backdrop is a cuttable wall in front of a live portal',`(()=>{loadLevel(10);if(!cutAt(0,0,-1))return false;at(0,-7.1);portalCross(new V(0,EYE,-6.9));return player.pos.x===42&&portals.length===2})()`);
test('Curved rising road has continuous supporting geometry',`(()=>{for(let i=1;i<=68;i++){const t=i/70,x=42+3.3*Math.sin(t*Math.PI*2),z=6-t*29;const y=groundAt(x,z,t*2.4+.3);if(!Number.isFinite(y)||Math.abs(y-t*2.4)>.2)return false;}return true})()`);
test('Standing view cannot claim seated moon observation',`(()=>{at(42,-23,4.05);aimAt(align.target);tickLevel(1.4);return !flags.moonRemembered})()`);
test('Sitting on observation chair allows moon to become a light photograph',`(()=>{at(42,-21,4.05);const chair=pickups.find(p=>p.userData.type==='seat'&&p.position.x===42);aimAt(chair.position.clone().add(new V(0,.8,0)));action();if(!seated)return false;aimAt(align.target);tickLevel(1.4);return flags.moonRemembered&&cards.some(c=>c.kind==='moon')})()`);
test('Moon copy really lights sensor while an echo holds the final position',`(()=>{seated=null;at(38,-25,4.05);toggleEcho();for(let i=0;i<10;i++)tickEcho(.1);toggleEcho();for(let i=0;i<20;i++)tickEcho(.1);if(!ghostAt('copy',46,-21,4.05))return false;place();settle();for(let i=0;i<100;i++)tickLevel(1/60);return actorPads[0].on&&sensors[0].on&&flags.moonExit&&gates[0].open})()`);
test('Final arch completes the six-chapter journey',`(()=>{complete();return won&&!active})()`);


// Guidance checks use actual puzzle state and keyboard/UI callbacks.
test('First-play movement and look teaching advances through real input state',`(()=>{loadLevel(6);guideLearned=false;guideMoved=false;guideLooked=false;if(currentGuide().id!=='walk')return false;player.pos.x+=1.5;if(currentGuide().id!=='look')return false;player.yaw+=.3;return currentGuide().id==='house-photo'&&guideLearned&&localStorage.getItem('borrowed-distance-controls')==='learned'})()`);
test('Guidance can be disabled and reenabled without changing a puzzle',`(()=>{active=true;const state=JSON.stringify({flags,objects:cubes.map(c=>c.position.toArray()),cards:cards.length});setGuidance(false);if(!$('guidePanel').hidden||!$('guideMarker').hidden||$('guideStart').checked||$('guidePause').checked||localStorage.getItem('borrowed-distance-guide')!=='off')return false;setGuidance(true);return !$('guidePanel').hidden&&$('guideStart').checked&&$('guidePause').checked&&state===JSON.stringify({flags,objects:cubes.map(c=>c.position.toArray()),cards:cards.length})})()`);
test('Detailed hints pause, persist, navigate and resume with guide off',`(()=>{setGuidance(false);active=true;begun=true;hint();if(active||!guideHintOpen||$('hintModal').hidden||!$('hintNow').textContent)return false;$('hintNext').onclick();if(guideHintIndex!==1||$('hintText').textContent!==chapters[level].hints[1])return false;closeGuideHint();const ok=active&&!guideHintOpen&&$('hintModal').hidden&&!guideEnabled;setGuidance(true);return ok})()`);
test('House guide follows capture, scaling, interior and missing-photo recovery',`(()=>{loadLevel(6);if(chapterGuide().id!=='house-photo')return false;addCard('copy','light',{kind:'lamp'});if(chapterGuide().id!=='house-scale')return false;homeToken.userData.size=3;if(chapterGuide().id!=='house-enter')return false;player.pos.x=38;if(chapterGuide().id!=='house-light')return false;cards=[];return chapterGuide().id==='house-return'})()`);
test('Negative guide recognizes crossing, recall and second use',`(()=>{loadLevel(7);pads[0].on=true;openCut(cutWalls[0],cards[0].id);if(chapterGuide().id!=='hedge-cross')return false;flags.mazeStage=1;at(-4,-3);if(chapterGuide().id!=='hedge-recall')return false;recall();return chapterGuide().id==='hedge-second'})()`);
test('Shadow guide rejects short photo and tracks clearing the caster',`(()=>{loadLevel(9);addCard('shadow','short',{length:4});if(chapterGuide().id!=='shadow-size')return false;cards=[];shadowCaster.userData.size=2.8;shadowCaster.scale.setScalar(2.8);shadowCaster.position.set(0,1.4,2.5);settle();tickLevel(.1);if(chapterGuide().id!=='shadow-capture')return false;addCard('shadow','long',{length:14});if(chapterGuide().id!=='shadow-clear')return false;shadowCaster.position.set(5,1.4,5);tickLevel(.1);return chapterGuide().id==='shadow-develop'})()`);
test('Moon guide distinguishes arrival, sitting, rising and echo',`(()=>{loadLevel(10);if(chapterGuide().id!=='moon-screen')return false;player.pos.x=42;if(chapterGuide().id!=='moon-seat')return false;seated=pickups.find(p=>p.userData.type==='seat');if(chapterGuide().id!=='moon-align')return false;flags.moonRemembered=true;if(chapterGuide().id!=='moon-rise')return false;seated=null;return chapterGuide().id==='moon-echo'})()`);
test('Held objects and photos show mode-specific controls',`(()=>{loadLevel(7);togglePhoto();if(!guideControls()[1].includes('白弧'))return false;stopPhoto();loadLevel(6);held={obj:homeToken};return guideControls()[1].includes(homeToken.userData.size.toFixed(2))})()`);
test('Resetting a chapter clears hint overlay but preserves guide preference',`(()=>{active=true;begun=true;hint();setGuidance(false);loadLevel(6);return !guideHintOpen&&$('hintModal').hidden&&!guideEnabled&&chapterGuide().id==='house-photo'})()`);

// Hands-on practice must be completed by real interactions, not a Next button.
test('Practice initializes safely and closing guidance does not skip lessons',`(()=>{startGame(11);guideLearned=true;const before=practice.stage;setGuidance(false);tickLevel(.1);if(practice.stage!==before||!$('practiceFacts').hidden)return false;setGuidance(true);return practice.stage===0&&cubes.length===1&&!gates[0].open})()`);
test('Practice requires walking into the marked circle and picking up the object',`(()=>{at(0,13);tickLevel(.1);if(practice.stage!==1)return false;const o=practiceOriginal();aimAt(o.position);action();tickLevel(.1);return held?.obj===o&&practice.stage===2})()`);
test('Practice enlargement works with actual perspective controls',`(()=>{player.pitch=0;syncCamera();changeDistance(7);updateHeld();tickLevel(.1);return practice.stage===3&&practiceOriginal().userData.size>=1.4})()`);
test('Practice pad validates a genuinely enlarged and dropped cube',`(()=>{const o=practiceOriginal(),d=1.5/held.ratio;player.pos.set(3,EYE,4+Math.sqrt(d*d-.9*.9));syncCamera();aimAt(new V(3,.75,4));held.distance=d;updateHeld();action();settle();tickLevel(.1);return practice.stage===4&&pads[0].on&&o.userData.size>=1.4})()`);
test('Practice photography, preview, manifestation and recall use actual actions',`(()=>{at(0,7);aimAt(practiceOriginal().position);capture();tickLevel(.1);if(practice.stage!==5)return false;at(-3,7);togglePhoto();updateGhost();tickLevel(.1);if(practice.stage!==6||!ghostValid)return false;place();tickLevel(.1);if(practice.stage!==7||cubes.length!==2)return false;recall();tickLevel(.1);return practice.stage===8&&cubes.length===1&&cards.some(c=>c.type==='copy')&&practice.bridgePickup})()`);
test('Practice bridge photo is collected, developed and physically crossed',`(()=>{at(0,-.5);aimAt(new V(0,1.8,-3));action();tickLevel(.1);if(practice.stage!==9)return false;if(!ghostAt('bridge',0,-5.5))return false;place();tickLevel(.1);if(practice.stage!==10)return false;at(0,-5.5);walk(220);tickLevel(.1);return practice.stage===11&&gates[0].open&&player.pos.z<-18&&player.pos.y>1.6})()`);

test('Chapter one exit advances to pool and persists the new campaign progress',`(()=>{unlocked=0;complete();return level===2&&!practice&&localStorage.getItem('borrowed-distance-iv')==='1'&&$('chapterTitle').textContent==='02 / 泳池来信'})()`);
test('Both guidance settings start the same first chapter',`(()=>{setGuidance(true);$('startBtn').onclick();if(level!==11)return false;toMenu();setGuidance(false);$('startBtn').onclick();return level===11&&practice.stage===0})()`);
test('Continue maps the saved ordinal to the intended scene',`(()=>{unlocked=3;$('continueBtn').onclick();return level===7&&$('chapterTitle').textContent==='04 / 留白花园'})()`);
test('Exactly six chapters advance in visible order to the ending',`(()=>{const titles=['借一个台阶','泳池来信','折叠的家','留白花园','影子成路','月光归档'];startGame();for(let i=0;i<6;i++){if(chapters[level].title!==titles[i]||$('chapterTitle').textContent.slice(0,2)!==String(i+1).padStart(2,'0'))return false;complete();}return won&&!active&&CAMPAIGN.length===6})()`);
test('Each public chapter has a concrete current instruction and finite target',`(()=>{guideLearned=true;for(const n of CAMPAIGN){loadLevel(n);active=true;begun=true;const s=chapterGuide();if(!s.title||!s.body||s.index>s.total||s.target&&!s.target.toArray().every(Number.isFinite))return false;renderGuidance();if(!$('guideBody').textContent)return false;}return true})()`);
test('Maze loops even on the correct branch until the size anchor is active',`(()=>{loadLevel(7);at(-4,-3);tickLevel(.1);if(player.pos.z!==13||flags.mazeStage!==0||chapterGuide().id!=='hedge-anchor')return false;const c=cubes[0];c.position.set(0,.475,7);settle();if(pads[0].on)return false;c.userData.size=.5;c.scale.setScalar(.5);c.position.set(0,.25,7);settle();at(-4,-3);tickLevel(.1);return flags.mazeStage===1&&pads[0].on})()`);
test('The redesigned chair can be targeted and sat on with the interaction ray',`(()=>{loadLevel(11);const s=pickups.find(p=>p.userData.type==='seat');at(s.position.x,s.position.z+2);aimAt(s.position.clone().add(new V(0,.8,0)));world.updateMatrixWorld(true);action();return seated===s&&Math.abs(player.pos.y-s.userData.view.y)<.01})()`);
test('All public spawn positions have real floor support',`(()=>{for(const n of CAMPAIGN){loadLevel(n);const expected=checkpoint.y-EYE;stepPlayer(1/60);if(!Number.isFinite(groundAt(player.pos.x,player.pos.z,expected+.3))||Math.abs(player.pos.y-checkpoint.y)>.1)return false;}return true})()`);
// The new visual system must preserve rendering state and non-color interaction cues.
test('Each chapter has a distinct chromatic architecture palette',`(()=>{const names=new Set();for(const n of CAMPAIGN){loadLevel(n);names.add(world.userData.palette);let colored=0;world.traverse(o=>{if(o.isMesh&&o.material?.color){const c=o.material.color;if(Math.max(c.r,c.g,c.b)-Math.min(c.r,c.g,c.b)>.08)colored++}});if(colored<25)return false;}return names.size===6})()`);
test('Water reflection mirrors camera and restores portal visibility across chapters',`(()=>{for(const n of CAMPAIGN){loadLevel(n);syncCamera();const before=portals.map(p=>p.mesh.visible),water=reflectingWater[0];renderWater(1000);if(!water.visible||!water.material.uniforms.ready.value||!water.material.uniforms.matrix.value.elements.every(Number.isFinite)||Math.abs(water.userData.reflectionCamera.position.y-(2*water.position.y-camera.position.y))>1e-6||portals.some((p,i)=>p.mesh.visible!==before[i]))return false;}return true})()`);
test('Valid and invalid photo locations expose distinct written cues',`(()=>{loadLevel(11);addCard('bridge','test');ghostAt('bridge',0,-5.5);updateArchitecture(0);if(!$('prompt').textContent.includes('✓ 可显影'))return false;ghostValid=false;updateArchitecture(1);return $('prompt').textContent.includes('× 位置未就绪')})()`);
test('Both flights of the new first-chapter staircase can be physically climbed',`(()=>{loadLevel(11);at(-9.3,11.6);walk(153);if(player.pos.y<6.1)return false;walk(49,'KeyD');player.yaw=Math.PI;syncCamera();walk(150);return player.pos.y>10.3&&player.pos.z>10})()`);
console.log('ALL PASSED: six ordered chapters, real collisions and puzzle actions, state-aware guidance, reset/recovery and offline assets.');
